### ISSUE TITLE
Catalog 500 Error on specific dataset?

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4444] opened 2023-09-01 20:38 UTC
catalog.data.gov @ main
ckanext-geodatagov @ v0.2.3

## How to reproduce

1. Visit https://catalog.data.gov/dataset/tiger-line-shapefile-2014-county-menifee-county-ky-address-ranges-county-based-relationship-fil

## Expected behavior

200?

## Actual behavior

500?
```bash
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT 2023-09-01 20:36:46,212 ERROR [ckan.config.middleware.flask_app]
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT Traceback (most recent call last):
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT rv = self.dispatch_request()
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/newrelic/hooks/framework_flask.py", line 82, in _nr_wrapper_handler_
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT return wrapped(*args, **kwargs)
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/config/middleware/../../views/dataset.py", line 499, in read
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT return base.render(
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/lib/base.py", line 107, in render
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR 2023-09-01 20:36:46,212 ERROR [ckan.config.middleware.flask_app]
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT return flask_render_template(template_name, **extra_vars)
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR Traceback (most recent call last):
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/newrelic/api/function_trace.py", line 166, in literal_wrapper
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT return wrapped(*args, **kwargs)
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT return _render(
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR rv = self.dispatch_request()
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT rv = template.render(context)
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/newrelic/api/function_trace.py", line 147, in dynamic_wrapper
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/newrelic/hooks/framework_flask.py", line 82, in _nr_wrapper_handler_
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT return wrapped(*args, **kwargs)
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR return wrapped(*args, **kwargs)
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/config/middleware/../../views/dataset.py", line 499, in read
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT self.environment.handle_exception()
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT raise rewrite_traceback_stack(source=source)
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR return base.render(
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/datagovtheme/templates/package/read.html", line 6, in top-level template code
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/lib/base.py", line 107, in render
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT {% set dataset_is_schema11 = h.get_pkg_dict_extra(c.pkg_dict, 'source_schema_version', '') == '1.1' %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR return flask_render_template(template_name, **extra_vars)
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/geodatagov/templates/package/read.html", line 3, in top-level template code
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT {% set pkg_dict = c.pkg_dict %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/newrelic/api/function_trace.py", line 166, in literal_wrapper
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/package/read.html", line 1, in top-level template code
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR return wrapped(*args, **kwargs)
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT {% extends "package/read_base.html" %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/datagovtheme/templates/package/read_base.html", line 1, in top-level template code
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR return _render(
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT {% extends "package/base.html" %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/datagovtheme/templates/package/base.html", line 3, in top-level template code
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR rv = template.render(context)
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT {% set pkg = c.pkg_dict %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/newrelic/api/function_trace.py", line 147, in dynamic_wrapper
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/datagovtheme/templates/page.html", line 1, in top-level template code
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR return wrapped(*args, **kwargs)
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT {% ckan_extends %} {% block maintag %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/page.html", line 1, in top-level template code
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR self.environment.handle_exception()
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT {% extends "base.html" %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/datagovtheme/templates/base.html", line 1, in top-level template code
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR raise rewrite_traceback_stack(source=source)
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT {% ckan_extends %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/datagovtheme/templates/package/read.html", line 6, in top-level template code
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/templates/base.html", line 1, in top-level template code
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR {% set dataset_is_schema11 = h.get_pkg_dict_extra(c.pkg_dict, 'source_schema_version', '') == '1.1' %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT {% ckan_extends %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/geodatagov/templates/package/read.html", line 3, in top-level template code
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR {% set pkg_dict = c.pkg_dict %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/base.html", line 108, in top-level template code
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/package/read.html", line 1, in top-level template code
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR {% extends "package/read_base.html" %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/datagovtheme/templates/package/read_base.html", line 1, in top-level template code
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT {%- block page %}{% endblock -%}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR {% extends "package/base.html" %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/page.html", line 19, in block 'page'
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/datagovtheme/templates/package/base.html", line 3, in top-level template code
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT {%- block content %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR {% set pkg = c.pkg_dict %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/page.html", line 22, in block 'content'
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/datagovtheme/templates/page.html", line 1, in top-level template code
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT {% block main_content %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR {% ckan_extends %} {% block maintag %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/page.html", line 74, in block 'main_content'
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT {% block primary %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/page.html", line 1, in top-level template code
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR {% extends "base.html" %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/datagovtheme/templates/base.html", line 1, in top-level template code
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR {% ckan_extends %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/templates/base.html", line 1, in top-level template code
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR {% ckan_extends %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/base.html", line 108, in top-level template code
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/page.html", line 87, in block 'primary'
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR {%- block page %}{% endblock -%}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT {% block primary_content %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/page.html", line 19, in block 'page'
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/datagovtheme/templates/package/read_base.html", line 59, in block 'primary_content'
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR {%- block content %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT {% block primary_content_inner %}{% endblock %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/page.html", line 22, in block 'content'
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR {% block main_content %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/package/read.html", line 34, in block 'primary_content_inner'
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/page.html", line 74, in block 'main_content'
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR {% block primary %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT {% block package_resources %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/datagovtheme/templates/package/read.html", line 113, in block 'package_resources'
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT {% block collection_resources %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/page.html", line 87, in block 'primary'
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/datagovtheme/templates/package/read.html", line 114, in block 'collection_resources'
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR {% block primary_content %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT {{ super() }}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/datagovtheme/templates/package/read_base.html", line 59, in block 'primary_content'
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/geodatagov/templates/package/read.html", line 14, in block 'collection_resources'
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR {% block primary_content_inner %}{% endblock %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/templates/package/read.html", line 34, in block 'primary_content_inner'
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT {% set collection_package = h.get_collection_package(collection_package_id) %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR {% block package_resources %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/geodatagov/helpers.py", line 62, in get_collection_package
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/datagovtheme/templates/package/read.html", line 113, in block 'package_resources'
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT package = p.toolkit.get_action('package_show')({}, {'id': collection_package_id})
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR {% block collection_resources %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/logic/__init__.py", line 551, in wrapped
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/datagovtheme/templates/package/read.html", line 114, in block 'collection_resources'
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT result = _action(context, data_dict, **kw)
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR {{ super() }}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/logic/action/get.py", line 1018, in package_show
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/geodatagov/templates/package/read.html", line 14, in block 'collection_resources'
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR {% set collection_package = h.get_collection_package(collection_package_id) %}
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT raise NotFound
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckanext/geodatagov/helpers.py", line 62, in get_collection_package
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] OUT ckan.logic.NotFound
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR package = p.toolkit.get_action('package_show')({}, {'id': collection_package_id})
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/logic/__init__.py", line 551, in wrapped
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR result = _action(context, data_dict, **kw)
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/logic/action/get.py", line 1018, in package_show
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR raise NotFound
   2023-09-01T16:36:46.21-0400 [APP/PROC/WEB/4] ERR ckan.logic.NotFound
```

## Sketch

Not sure...

**Comment by nickumia-reisys** [comment] 2023-09-01 20:44
Other examples:
- https://catalog.data.gov/dataset/generalized-map-of-surficial-materials-in-northwestern-riverside-and-southwestern-san-bernardin
- https://catalog.data.gov/dataset/tiger-line-shapefile-2013-county-lake-county-mn-all-roads-county-based-shapefile
- https://catalog.data.gov/dataset/tiger-line-shapefile-2014-county-woodbury-county-ia-all-roads-county-based-shapefile
- https://catalog.data.gov/dataset/rosetta.sqlite
- https://catalog.data.gov/dataset/rosetta.sqlitedb 
- https://catalog.data.gov/dataset/u-s-electric-utility-companies-and-rates-look-up-by-zipcode-2020.z

**Comment by FuhuXia** [comment] 2023-09-01 20:47
duplicate of https://github.com/GSA/data.gov/issues/2273

**Comment by FuhuXia** [comment] 2023-09-01 20:55
This [example dataset](https://catalog.data.gov/dataset/tiger-line-shapefile-2014-county-menifee-county-ky-address-ranges-county-based-relationship-fil) belongs to a [collection](https://catalog.data.gov/dataset/tiger-line-shapefile-2014-series-information-file-for-the-address-ranges-county-based-relations), the collection itself has been deleted. Maybe that is the scenario to cause the 500 error, all children dataset gives 500 error if parent collection is deleted?

**Comment by Jin-Sun-tts** [comment] 2024-01-18 18:18
duplicate issue as https://github.com/GSA/data.gov/issues/4553.

**Closed as completed by Jin-Sun-tts** 2024-01-18 18:18 UTC
Labels: bug, O&M
