### ISSUE TITLE
Inventory-next Bad Request error

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2278] opened 2020-10-13 16:57 UTC
Intermittently seeing `Invalid HTTP header` errors when logging into inventory-next, or when browsing with an active logged-in session. 

## How to reproduce

Intermittent. Only seen in sandbox for far.
Go to https://inventory-next.sandbox.datagov.us/ and log in.

## Expected behavior

Login happens with no messages. 

## Actual behavior

After login the page shows error messages such as:

```
Bad Request
Invalid HTTP Header: '\'SameSite=lax\\r\\nauth_tkt="e3ee8cf439ca37edecb45d2dbc3bc0105f85d796fxia!userid_type=unicode"; expires=Thu, 13 Oct 2022 16:36:38 GMT; HttpOnly; Max-Age=63072000; Path=/; SameSite=Lax\''
```
or
```
Bad Request
Invalid HTTP Header: '\'SameSite=lax\\r\\nauth_tkt="d837b8a8a6f2e9a1b82bd0d11a1d0fb85f85d97efxia!userid_type=unicode"; HttpOnly; Path=/; SameSite=Lax\''
```

**Comment by FuhuXia** [comment] 2020-10-13 21:18
Seen on staging as well.

**Comment by jbrown-xentity** [comment] 2020-10-19 21:42
Unable to reproduce in sandbox (spent 10 minutes clicking around on every possible link).

**Comment by jbrown-xentity** [comment] 2020-10-26 20:31
Has not been reproduceable in a while. Closing unless issue is seen again.

**Closed as completed by jbrown-xentity** 2020-10-26 20:31 UTC
Labels: bug
