### ISSUE TITLE
Add host-level smoke tests for health check endpoints

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2484] opened 2020-11-24 23:22 UTC
## User Story

In order to ensure that applications are responding to load balancer health checks after a successful deploy, data.gov operator wants host-level smoke tests in the Ansible playbooks.

## Acceptance Criteria
- [ ] WHEN the application playbooks are run
  THEN the playbook checks for a successful health check endpoint before moving onto the next host

## Background
From the 2020-10-14 Incident:
https://docs.google.com/document/d/19YhtdNZ3x9n3FJLWmue3XH9drxn8PVTHGnpeu-gdtao/edit#

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch
Add additional host-level checks for all applications. Should be a HEAD request on the IP address of the host.

catalog HEAD /api/action/package_search?rows=1 200
inventory: HEAD / 302
wordpress: HEAD / 301
dashboard: HEAD /dashboard/healthcheck 200

**Comment by adborden** [comment] 2020-12-03 21:08
@FuhuXia recently created a spreadsheet with updated [health check points](https://docs.google.com/spreadsheets/d/1Qee_TQuLGEASnZ08v1rLBf47kes2KDSoPPTphfXNfc4).

**Comment by jbrown-xentity** [comment] 2020-12-17 21:27
Closing as duplicate of #2432 .

**Closed as completed by jbrown-xentity** 2020-12-17 21:27 UTC
