### ISSUE TITLE
data.json harvester should delete a dataset if it is not in the source

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2989] opened 2021-03-12 22:15 UTC
A harvested data.json dataset should be deleted on next harvest job if it is deleted from source.

## How to reproduce

1. Harvest from a data.json source
2. Delete a dataset from then source then harvest again

## Expected behavior

1 dataset deleted

## Actual behavior

0 dataset deleted

**Comment by FuhuXia** [comment] 2021-03-12 22:20
Gather process failed to detect a deleted dataset from source.
```
DEBUG [ckanext.harvest.queue] Received harvest job id: fdbab707-8078-4da5-a670-529b493ba8f7
DEBUG [ckanext.datajson.datajson_ckan_28] In <Plugin DataJsonHarvester 'datajson_harvest'> gather_stage (http://[...])
INFO  [ckanext.harvest.queue] No harvest objects to fetch
```

**Comment by FuhuXia** [comment] 2022-11-23 15:46
DOC harvest source cleaned up their records and there are about 1.5k in the data.json source. After a successful harvest job, 9k datasets were deleted but there are 14k dataset remaining. It should be only 1.5 datasets remaining. So this bug is affecting some datasets but no the others.

**Comment by jbrown-xentity** [comment] 2022-12-08 21:28
Duplicate of #4050

**Comment by nickumia-reisys** [comment] 2022-12-13 16:28
> A newly set up source in the Development space works fine.

Given that this does not effect a newly created harvest source, could this be an effect of changes to the data model from CKAN 2.3 to 2.8 to 2.9?

**Comment by FuhuXia** [comment] 2022-12-13 16:36
Could be. So it may have been fixed for newly created datasets, but how to make the harvester detect and delete old datasets?

**Comment by FuhuXia** [comment] 2023-01-10 14:57
Got this figured out. The issue does not affect a clean system. But on a system where there were duplicate data.json records (multiple datasets with same `identifier`) and later on a de-dupe process was run, those datasets deleted by the de-dupe process remain in the deleted state, causing this issue when gather process is checking the existing datasets against the source. Basically the gather process is checking deleted record with already deleted packages, therefore no action taken. We can fix this by modifying gather process to make sure the checking process is checking with active packages, if any.

This also shows that deleted packages remaining in the ckan system are affecting harvesting performance, we should develop a purge schedule. Will create another ticket for it.

**Comment by FuhuXia** [comment] 2023-01-11 16:27
Deployed on prod. Running a manual re-harvest.  Will evaluate result after the reharvest is done.

This is before reharvest, **14390** records:
![image](https://user-images.githubusercontent.com/1392461/211860604-d8a183b7-7fe7-49e2-8dad-747414be4467.png)

**Comment by FuhuXia** [comment] 2023-01-11 22:17
Manually run multiple times. As a result, DOC harvested dataset is matching what is in the source.

![image](https://user-images.githubusercontent.com/1392461/211929762-c71600cf-62e0-462a-b12f-8b5879f47169.png)

**Closed as completed** 2023-01-19 18:15 UTC
Labels: bug
