### ISSUE TITLE
Jsonschema harvester doesn't harvest dataset having { in data

### ISSUE THREAD

**Issue by ydave-reisys** [GSA/data.gov#1393] opened 2020-02-20 18:51 UTC
## How to reproduce

1. Description of steps to reproduce the issue.
e.g USDA json harvester

**Comment by mogul** [comment] 2020-02-20 21:39
Because customers have a workaround for this issue (eliminate unquoted `{` in their URLs and JSON content) we're choosing to put this in the `Icebox`. @hkdctol will contact the two customers we know have run into this issue to inform them of the workaround.

**Comment by FuhuXia** [comment] 2020-03-30 14:24
Upon further research, the cause of issue is the unencoded characters used in `uri` type of fields. the offending chars in USDA json include `{`, `}`, `\"`, and more than 1 set of `&#`.

**Comment by FuhuXia** [comment] 2020-03-30 14:30
Our JSON schema validator used in ckanext-datajson is working correctly to pick up those chars. its behavior is consistent with other online validator I tried. 
![Screenshot 2020-03-30 10 20 27](https://user-images.githubusercontent.com/1392461/77923822-f923d480-7270-11ea-8817-6992378d5ed5.png)
So the question is why the [validator on Project Open Data Dashboard](https://labs.data.gov/dashboard/validate) does not report validation error on those records. will open a separate issue for that.

**Comment by FuhuXia** [comment] 2020-03-30 15:24
Issue opened on Project Open Data dashboard repo. https://github.com/GSA/project-open-data-dashboard/issues/262

**Comment by adborden** [comment] 2020-04-01 21:48
@FuhuXia based on your understanding of the issue, the work around would be for agencies to use [URL encoding](https://en.wikipedia.org/wiki/Percent-encoding) for URLs, is that correct?

**Comment by FuhuXia** [comment] 2020-04-01 23:33
@adborden It is not a workaround. The querystrings in the URI **MUST** to be correctly encoded. Otherwise, those bad characters will get the dataset invalidated by Project Open Data validator (if the [issue](https://github.com/GSA/project-open-data-dashboard/issues/262) is fixed), or will later be rejected by catalog harvester as it is happening now.

Depending on what URI encoding tool agencies are using, it has be done correctly. Only the values in querystring part should be encoded, not the protocol, host, path...part. 

For example,
`http://abc.com/datasets/a123.geojson?outSR={"aa":1,"bb":2}`
should be encoded as
`http://abc.com/datasets/a123.geojson?outSR=%7B%22aa%22%3A1%2C%22bb%22%3A2%7D`
  
If there are any doubts, use this [online tool](https://www.jsonschemavalidator.net/) to test, as shown in the screenshot I attached above.

**Comment by FuhuXia** [comment] 2020-05-15 15:17
> Issue opened on Project Open Data dashboard repo. [GSA/project-open-data-dashboard#262](https://github.com/GSA/project-open-data-dashboard/issues/262)

Closing this issue since it is being tracked elsewhere.

**Closed as completed by FuhuXia** 2020-05-15 15:17 UTC
Labels: component/catalog
