### ISSUE TITLE
Ubuntu AMI bug fixes

### ISSUE THREAD

**Issue by neilhunt1** [GSA/data.gov#38] opened 2016-11-07 20:13 UTC
Dan reported the following issues with the current Ubuntu AMI
1.	git is unusable: this one I have worked on and this and I get it to function correctly, however it seems to be affected by Packer build because after Packer builds, git doesn't seem to work. Will retry it without packer since I'm not sure Packer is critical anymore.
2.	there is an issue with hostaname resolution (will try this solution: echo 127.0.0.1 $(hostname) >> /etc/hosts)
3.	Sometimes I can’t install packages (will try this solution: sed -i '/postdrop/d' /var/lib/dpkg/statoverride && sed -i '/ssl-cert/d' /var/lib/dpkg/statoverride)

**Comment by neilhunt1** [comment] 2016-11-07 21:12
@dano-reisys can you give a little more info on 2 above? What is the hostname issue? Do you want a specific entry in /etc/hosts such as:
"127.0.0.1 ip-10-0-0-84"
or do you want
"127.0.0.1 $(hostname)"
If the former, then it will need to run as some kind of instance startup script such as EC2 userdata. If the latter, that is easy and I can put into AMI.

**Comment by neilhunt1** [comment] 2016-11-07 21:17
@dano-reisys for item 3 above, more info would be helpful. Let me know when you get to a specific package that won't install correctly. I did run that command directly on the latest AMI so maybe that will help.

**Comment by dano-reisys** [comment] 2016-11-07 21:21
#2 https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=unable%20to%20resolve%20host%20ec2

same exact issue, i do not know the root cause.

**Comment by dano-reisys** [comment] 2016-11-07 21:39
#3 happened to me twice, i am not sure yet how to reproduce this, but there is def something wrong with it dpkg + hardening

**Comment by JJediny** [comment] 2016-11-07 21:44
@dano-reisys #2 Is this what your seeing? https://github.com/ansible/ansible-modules-core/issues/2308

```
- name: Update hosts file
  lineinfile: dest=/etc/hosts line="127.0.0.1 {{ec2_tag_Name}}"
              insertafter="^127\.0\.0\.1 localhost.*$"
  when: ec2_tag_Name is defined
```

**Comment by dano-reisys** [comment] 2016-11-07 22:41
#3 

root@ip-10-183-1-8:/home/ubuntu# apt-get remove git && apt-get install git
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'git' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  git-man liberror-perl libgmp10 python-crypto python-httplib2 python-jinja2
  python-markupsafe python-paramiko sshpass
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libgmp10 python-crypto python-httplib2 python-jinja2 python-markupsafe
  python-paramiko sshpass
Use 'apt-get autoremove' to remove them.
Suggested packages:
  git-daemon-run git-daemon-sysvinit git-doc git-el git-email git-gui gitk
  gitweb git-arch git-bzr git-cvs git-mediawiki git-svn
The following NEW packages will be installed:
  git
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 0 B/2,586 kB of archives.
After this operation, 20.5 MB of additional disk space will be used.
dpkg: unrecoverable fatal error, aborting:
 syntax error: unknown group 'postdrop' in statoverride file
E: Sub-process /usr/bin/dpkg returned an error code (2)
root@ip-10-183-1-8:/home/ubuntu#

**Comment by dano-reisys** [comment] 2016-11-07 22:49
#1 

looks like there might be other packages affected... i believe there is a similar problem with sendmail, we need to find the root cause.

**Comment by dano-reisys** [comment] 2016-11-07 22:50
@JJediny don't think #2 has anything to do with ansible.

**Comment by neilhunt1** [comment] 2016-11-08 12:04
#1 may be related to the packer process, I am going to push one directly later today (Not published through packer) so we'll try that out since Packer isn't really critical anymore.
#2 I have seen this before myself. I would like to fix it but like you said it appears even with base ubuntu image. Though I haven't noticed any adverse behavior by it, have you?
#3 I'll look at this more today. http://askubuntu.com/questions/335538/unknown-user-in-statoverride-file

**Comment by neilhunt1** [comment] 2016-11-10 13:09
Think I've figured out no. 3; related to the disk partitioning scheme I setup in order to pump logs/tmp/var/home/etc to their own partitions. Working on fixing that today.
No. 2 is a known issue, but Dan's suggestion of adding the exact hostname does seem to work. But this may be a required step for each instance, since obviously we can't bake the hostname into the AMI
Still trying to reproduce no. 1

**Comment by neilhunt1** [comment] 2016-11-14 15:07
Two more AMI's are ready: 
ami-857f5392 - Ubuntu 14.04 pre-CIS. This has everything except has not had the CIS hardening playbook executed.
ami-b9062fae - Ubuntu 14.04 post-hardening: This is the same as the above, but already had had the CIS hardening playbook executed.
Please start using these and let me know if you have any issues.

**Comment by neilhunt1** [comment] 2016-11-14 19:28
@dano-reisys will be standing up one or more data.gov services in our sandbox using the new AMIs. Assigning this to him for verification of any issues.

**Comment by dano-reisys** [comment] 2016-11-23 18:30
I've gotten the same error as I did before while it was trying to install postfix (dashboard-web.yml), it seems like there is still something going on with dpkg.

fatal: [54.211.8.45]: FAILED! => {"cache_update_time": 0, "cache_updated": false, "changed": false, "failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'sendmail'' failed: dpkg: postfix: dependency problems, but removing anyway as you requested:\n bsd-mailx depends on default-mta | mail-transport-agent; however:\n  Package default-mta is not installed.\n  Package postfix which provides default-mta is to be removed.\n  Package mail-transport-agent is not installed.\n  Package postfix which provides mail-transport-agent is to be removed.\n bsd-mailx depends on default-mta | mail-transport-agent; however:\n  Package default-mta is not installed.\n  Package postfix which provides default-mta is to be removed.\n  Package mail-transport-agent is not installed.\n  Package postfix which provides mail-transport-agent is to be removed.\n\ninvoke-rc.d: unknown initscript, /etc/init.d/postfix not found.\ndpkg: error processing package postfix (--remove):\n subprocess installed pre-removal script returned error exit status 100\n/var/lib/dpkg/info/postfix.postinst: 13: .: Can't open /usr/share/postfix/postinst.functions\ndpkg: error while cleaning up:\n subprocess installed post-installation script returned error exit status 2\nErrors were encountered while processing:\n postfix\nE: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stderr": "dpkg: postfix: dependency problems, but removing anyway as you requested:\n bsd-mailx depends on default-mta | mail-transport-agent; however:\n  Package default-mta is not installed.\n  Package postfix which provides default-mta is to be removed.\n  Package mail-transport-agent is not installed.\n  Package postfix which provides mail-transport-agent is to be removed.\n bsd-mailx depends on default-mta | mail-transport-agent; however:\n  Package default-mta is not installed.\n  Package postfix which provides default-mta is to be removed.\n  Package mail-transport-agent is not installed.\n  Package postfix which provides mail-transport-agent is to be removed.\n\ninvoke-rc.d: unknown initscript, /etc/init.d/postfix not found.\ndpkg: error processing package postfix (--remove):\n subprocess installed pre-removal script returned error exit status 100\n/var/lib/dpkg/info/postfix.postinst: 13: .: Can't open /usr/share/postfix/postinst.functions\ndpkg: error while cleaning up:\n subprocess installed post-installation script returned error exit status 2\nErrors were encountered while processing:\n postfix\nE: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following packages were automatically installed and are no longer required:\n  linux-headers-3.13.0-91 linux-headers-3.13.0-91-generic\n  linux-image-3.13.0-91-generic\nUse 'apt-get autoremove' to remove them.\nThe following extra packages will be installed:\n  m4 make procmail sendmail-base sendmail-bin sendmail-cf sensible-mda\nSuggested packages:\n  make-doc sendmail-doc rmail logcheck sasl2-bin\nThe following packages will be REMOVED:\n  postfix\nThe following NEW packages will be installed:\n  m4 make procmail sendmail sendmail-base sendmail-bin sendmail-cf\n  sensible-mda\n0 upgraded, 8 newly installed, 1 to remove and 16 not upgraded.\nNeed to get 1158 kB of archives.\nAfter this operation, 1426 kB of additional disk space will be used.\nGet:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main m4 amd64 1.4.17-2ubuntu1 [195 kB]\nGet:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main make amd64 3.81-8.2ubuntu3 [119 kB]\nGet:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/universe sendmail-base all 8.14.4-4.1ubuntu1 [139 kB]\nGet:4 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/universe sendmail-cf all 8.14.4-4.1ubuntu1 [86.1 kB]\nGet:5 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/universe sendmail-bin amd64 8.14.4-4.1ubuntu1 [469 kB]\nGet:6 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main procmail amd64 3.22-21ubuntu0.1 [135 kB]\nGet:7 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/universe sensible-mda amd64 8.14.4-4.1ubuntu1 [8246 B]\nGet:8 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/universe sendmail all 8.14.4-4.1ubuntu1 [6248 B]\nFetched 1158 kB in 0s (12.2 MB/s)\nSelecting previously unselected package m4.\n(Reading database ... 105142 files and directories currently installed.)\nPreparing to unpack .../m4_1.4.17-2ubuntu1_amd64.deb ...\nUnpacking m4 (1.4.17-2ubuntu1) ...\nSelecting previously unselected package make.\nPreparing to unpack .../make_3.81-8.2ubuntu3_amd64.deb ...\nUnpacking make (3.81-8.2ubuntu3) ...\nSelecting previously unselected package sendmail-base.\nPreparing to unpack .../sendmail-base_8.14.4-4.1ubuntu1_all.deb ...\nUnpacking sendmail-base (8.14.4-4.1ubuntu1) ...\nSelecting previously unselected package sendmail-cf.\nPreparing to unpack .../sendmail-cf_8.14.4-4.1ubuntu1_all.deb ...\nUnpacking sendmail-cf (8.14.4-4.1ubuntu1) ...\nProcessing triggers for man-db (2.6.7.1-1ubuntu1) ...\nProcessing triggers for install-info (5.2.0.dfsg.1-2) ...\n(Reading database ... 105572 files and directories currently installed.)\nRemoving postfix (2.11.0-1ubuntu1) ...\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following packages were automatically installed and are no longer required:", "  linux-headers-3.13.0-91 linux-headers-3.13.0-91-generic", "  linux-image-3.13.0-91-generic", "Use 'apt-get autoremove' to remove them.", "The following extra packages will be installed:", "  m4 make procmail sendmail-base sendmail-bin sendmail-cf sensible-mda", "Suggested packages:", "  make-doc sendmail-doc rmail logcheck sasl2-bin", "The following packages will be REMOVED:", "  postfix", "The following NEW packages will be installed:", "  m4 make procmail sendmail sendmail-base sendmail-bin sendmail-cf", "  sensible-mda", "0 upgraded, 8 newly installed, 1 to remove and 16 not upgraded.", "Need to get 1158 kB of archives.", "After this operation, 1426 kB of additional disk space will be used.", "Get:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main m4 amd64 1.4.17-2ubuntu1 [195 kB]", "Get:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main make amd64 3.81-8.2ubuntu3 [119 kB]", "Get:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/universe sendmail-base all 8.14.4-4.1ubuntu1 [139 kB]", "Get:4 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/universe sendmail-cf all 8.14.4-4.1ubuntu1 [86.1 kB]", "Get:5 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/universe sendmail-bin amd64 8.14.4-4.1ubuntu1 [469 kB]", "Get:6 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main procmail amd64 3.22-21ubuntu0.1 [135 kB]", "Get:7 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/universe sensible-mda amd64 8.14.4-4.1ubuntu1 [8246 B]", "Get:8 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/universe sendmail all 8.14.4-4.1ubuntu1 [6248 B]", "Fetched 1158 kB in 0s (12.2 MB/s)", "Selecting previously unselected package m4.", "(Reading database ... 105142 files and directories currently installed.)", "Preparing to unpack .../m4_1.4.17-2ubuntu1_amd64.deb ...", "Unpacking m4 (1.4.17-2ubuntu1) ...", "Selecting previously unselected package make.", "Preparing to unpack .../make_3.81-8.2ubuntu3_amd64.deb ...", "Unpacking make (3.81-8.2ubuntu3) ...", "Selecting previously unselected package sendmail-base.", "Preparing to unpack .../sendmail-base_8.14.4-4.1ubuntu1_all.deb ...", "Unpacking sendmail-base (8.14.4-4.1ubuntu1) ...", "Selecting previously unselected package sendmail-cf.", "Preparing to unpack .../sendmail-cf_8.14.4-4.1ubuntu1_all.deb ...", "Unpacking sendmail-cf (8.14.4-4.1ubuntu1) ...", "Processing triggers for man-db (2.6.7.1-1ubuntu1) ...", "Processing triggers for install-info (5.2.0.dfsg.1-2) ...", "(Reading database ... 105572 files and directories currently installed.)", "Removing postfix (2.11.0-1ubuntu1) ..."]}

**Comment by neilhunt1** [comment] 2016-11-23 20:45
Weird. Dan, is this in our OCSIT env and if so can you give me instance ID?

**Comment by dano-reisys** [comment] 2016-12-20 06:08
Both ntp and postfix haven't been removed properly. I can't remove either of them successfully through apt-get

**Closed as completed** 2017-02-02 22:12 UTC
