### ISSUE TITLE
Non-federal source (Fairfax County) being changed to federal in catalog

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1135] opened 2019-11-19 20:33 UTC
A non-federal source, Fairfax County data.json, had been created as a non-federal source originally, but appears as federal, and when I change to non-federal and save through admin UI, the change is not taking effect.

## How to reproduce

1. Log in as admin user on catalog.data.gov, and try to edit the Fairfax County data.json harvest source.

## Expected behavior
Admin user should be able to change to non-federal and save

## Actual behavior

Can hit save button, but the change to non-federal does not take.
![fairfax](https://user-images.githubusercontent.com/3236989/69183896-d2df7280-0ae1-11ea-8ebf-3afff11fe221.png)
-->

**Comment by hkdctol** [comment] 2019-11-22 22:02
Just checked to see if it was momentary error -- still not able to save a change to non-federal source through admin UI.

**Comment by hkdctol** [comment] 2019-12-26 23:31
Same problem observed today with Sioux Falls, SD source and Lake County, IL source

**Comment by hkdctol** [comment] 2020-01-15 16:32
We have some weekly harvests that ran with other non-federal sources today, and they seem to be all showing the same problem. When I change to non-federal through UI, the change appears to save but it doesn't. Chatting with @JJediny who is at next desk today, he suggests it could be that the choice of "non-federal" as validation option isn't available so harvester is going with the default which is federal.

**Comment by hkdctol** [comment] 2020-01-25 02:44
Looks like a pervasive issue. Just did a reharvest of State of California data.json - and in UI it is set to federal instead of non-federal validation, and a change isn't really saved. Result was a large number of errors in the harvest report.

**Comment by jbrown-xentity** [comment] 2020-02-03 23:32
The UI is for some reason defaulting to "Federal" for the datajson harvest types, even if the database config has saved it as "non-federal". This can be seen by examining the config value in the about page for a harvest source (vs the edit page, which is showing the "default"). The UI seems to be built from a variety of sources, including:
https://github.com/GSA/ckanext-geodatagov/blob/master/ckanext/geodatagov/templates/source/geodatagov_source_form.html#L8
https://github.com/GSA/ckanext-harvest/blob/datagov/ckanext/harvest/helpers.py#L94
https://github.com/GSA/ckanext-datajson/blob/datagov/ckanext/datajson/harvester_base.py#L107
Still not sure what the issue is, need to integrate debugger and test to see where pieces are not be evaluated properly.

In the meantime, State of California data.json is being re-harvested as a test.

**Comment by hkdctol** [comment] 2020-02-04 22:08
Tried to see if the errors for non-federal sources happened at the same time--so far no. Compared Sioux Falls and Lake County and in one the large numbers of errors began in mid December and continued through regularly scheduled harvests, and in the other it was back in July 2019.

**Comment by hkdctol** [comment] 2020-02-04 22:20
From looking at other non-federal sources that have NOT reached out to us recently, it looks like on UI everything is set to federal instead of non-federal. Overall the sources with large number of harvest errors--they have errors independent of validation being set mistakenly to non-federal.

**Comment by jbrown-xentity** [comment] 2020-02-04 23:47
It looks like this has something to do with the config object... Looking at the code, it is expecting something like `validator_profiles` in the config object, otherwise it takes the default. All the POD harvest sources have a config object called `validator_schema`. Still not sure what's going on or where the change occurred...
I have been unable to get staging pulled up to verify that the issue is only on production. @ydave-reisys are you positive this issue is related only to production? The data seems consistent across staging and production...

**Comment by adborden** [comment] 2020-02-06 20:26
Kind of a shot in the dark, but in terms of validation profiles, there was some logic that did change recently https://github.com/GSA/ckanext-geodatagov/pull/120/files#diff-0a7fe5c5b0e4074fed9933c099cade52L37

I'm 100% sure if this was actually deployed to production or not.

**Comment by mogul** [comment] 2020-02-06 21:16
We're going to see if harvesting for non-federal agencies is happening. So long as that's happening, we'll move on from this bug and leave it be.

**Comment by jbrown-xentity** [comment] 2020-02-10 19:00
Harvesting is continuing as designed, the harvest errors are not related to a federal vs non-federal validation issue. This bug is still outstanding, but not deemed a high priority because the harvest process still works as expected. Moving to ice box.

**Comment by jbrown-xentity** [comment] 2020-08-04 16:50
Related to #1974

**Comment by avdata99** [comment] 2020-08-20 17:49
This was solved several weeks ago and have [some related tests](https://github.com/GSA/ckanext-geodatagov/blob/master/ckanext/geodatagov/tests/test_source_form.py). I think this issue should be QA'd and closed.
It's working at new catalog.

**Comment by pjsharpe07** [comment] 2020-09-04 22:06
@avdata99 @jbrown-xentity I just checked and it looks like this issue is resovled. Can I close this?

**Closed as completed** 2020-09-04 22:21 UTC
Labels: bug, support
