### ISSUE TITLE
NetSparker: jQuery version on www.data.gov CloudFront  error page is outdated

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1162] opened 2019-11-28 01:09 UTC
From the [www.data.gov Netsparker November report](https://drive.google.com/open?id=0B5EC5Q83gYbodGM3Qk5Za1pHVEstN0RlcF9SQmJJOEowNTVJ), jQuery is being listed as outdated (1.10.4) on https://www.data.gov/app/plugins/simple-tooltips/. This page is returning a 500, which is served by CloudFront and not WordPress.

I'm not sure how this error page was originally generated, but WordPress is serving jQuery 3.4.1.

**Comment by mogul** [comment] 2020-01-13 18:32
@adborden same question here: Do we have access to manipulate Cloudfront on our own if it turns out that clearing the cache is enough to resolve this?

**Comment by adborden** [comment] 2020-01-14 16:43
We can access this from the `gsaoppprod` account.

**Comment by jbrown-xentity** [comment] 2020-01-30 23:10
The 500 error pages for catalog and www.data.gov were discovered in s3, not currently managed. Pulled out relevant code, will load to GitHub for longer term management and document.
Either we will update jquery to latest version, or remove for simplicity.
@adborden is accomplishing the latter.

**Comment by jbrown-xentity** [comment] 2020-02-04 23:10
Confirmed on production via link in description, and noting jquery upgraded to 1.12. Marking as resolved.

**Closed as completed** 2020-02-06 18:41 UTC
Labels: compliance, bug
