### ISSUE TITLE
WIP: Develop Extract for WAF dataset records

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4258] opened 2023-03-23 21:29 UTC
## User Story

In order to harvest data from a WAF harvest source, data.gov wants a function that can pull all relevant xml links and files from a Web Accessible Folder (WAF).

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN a URL is supplied to a compliant WAF (https://data.noaa.gov/waf/NOAA/NESDIS/ncei/gis/iso/xml/) \
  WHEN the function executes \
  THEN each relevant file is saved locally
  AND there is a test repeating this process to verify this logic

## Background

[Current logic](https://github.com/ckan/ckanext-spatial/blob/master/ckanext/spatial/harvesters/waf.py#L53-L178)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch

We may want to consider various scraper tools to see what makes sense in the current python world (assume old logic is 5+ years out of date). Don't have to recreate the wheel however, if the current libraries seem maintained.

In general, we are looking to capture all xml files. Anything that isn't that, can probably be safely excluded. These files will probably (in the future) be passed onto a queue, but that queue logic is still TBD.

In order to create a repeatable test, you can create a local test server like we did for catalog. See test files [here](https://github.com/GSA/catalog.data.gov/tree/main/tests/harvest-sources) and mock server [here](https://github.com/GSA/catalog.data.gov/blob/main/docker-compose.yml#L49-L53) and [here](https://github.com/GSA/catalog.data.gov/blob/main/tests/nginx.conf).

**Comment by rshewitt** [comment] 2023-05-15 17:33
Should the test WAF include a folder to traverse into? The current example appears to be flat ( https://data.noaa.gov/waf/NOAA/NESDIS/ncei/gis/iso/xml/ )

**Comment by jbrown-xentity** [comment] 2023-05-16 13:56
I would say over 75% are flat, but we need to be able to handle the traversal use case. All the NOAA one's seem to be flat... This one is a possible example: https://hazards.fema.gov/filedownload/metadata/. Currently FEMA isn't using this feature, they [split up all their harvest sources](https://catalog.data.gov/harvest/?source_type=waf&organization=fema-gov) into individual regions (folders in the waf), but there's no reason we can't harvest the whole thing.

**Comment by btylerburton** [comment] 2023-05-26 22:07
Let's focus on extraction of a DCAT record first. Moving this back to the backlog.

**Comment by rshewitt** [comment] 2024-01-04 15:57
duplicate of [#4558](https://github.com/GSA/data.gov/issues/4558)?

**Comment by btylerburton** [comment] 2024-01-04 17:25
I believe so. As long as you feel like the other ticket captures all of the AC and context,  please close.

**Closed as completed** 2024-01-04 21:11 UTC
