### ISSUE TITLE
Deep pagination long load

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#3642] opened 2022-01-13 19:17 UTC
On datasets pages on catalog on cloud.gov, jumping to deeper pagination results causes long page load and page error (especially the higher pages) . Seems to return suspiciously just after 1min, probably something timing out and returning there. 

## How to reproduce

Description of steps to reproduce the issue.

1. Visit a page like [https://catalog-prod-datagov.app.cloud.gov/dataset/?page=1800](https://catalog-prod-datagov.app.cloud.gov/dataset/?page=1800)

## Expected behavior

Quick response: 

![image](https://user-images.githubusercontent.com/91547795/149394774-1d6f785c-b7c8-431d-b2ff-2eb7d513a2e8.png)

## Actual behavior

Slow response: 

![image](https://user-images.githubusercontent.com/91547795/149394730-9e1ab2af-dbe4-46d7-9261-1783df54dded.png)

Or quick response, but 504 error:

![image](https://user-images.githubusercontent.com/91547795/149394861-269d0766-8e2e-432a-8576-24f9157d8025.png)

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

Probably related to https://github.com/GSA/datagov-deploy/issues/3636

**Comment by jbrown-xentity** [comment] 2022-01-13 21:25
Closing as dupe of #3636

**Closed as completed by jbrown-xentity** 2022-01-13 21:25 UTC
Labels: bug
