### ISSUE TITLE
Enable ping monitors on critical data.gov sites

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#539] opened 2018-12-13 18:59 UTC
Ping monitors test APIs and transactions from different locations around the globe and alarm if the ping fails. This would alert us when any data.gov site goes down, but also would be able to test from different countries to ensure there's no connectivity issues.

New Relic has a [Synthetics](https://docs.newrelic.com/docs/synthetics) product that we've used in the past at 18F.

**Comment by JJediny** [comment] 2018-12-13 20:10
We've been using Uptrends which is a ping service provided by GSA IT, we recently expanded the scope of probing internationally to address this oversight

**Comment by adborden** [comment] 2018-12-14 01:03
Awesome, so we've already configured the international pings?

**Comment by adborden** [comment] 2018-12-14 16:54
Just noticed that uptrends are testing the direct BSP urls, so they miss some issues, like the firewall issues we ran into recently.

**Comment by adborden** [comment] 2018-12-17 18:39
Add an additional endpoint for catalog.data.gov

**Comment by adborden** [comment] 2019-02-11 18:11
I don't think labs.data.gov/dashboard has a monitor.

**Comment by hkdctol** [comment] 2020-05-20 18:45
Closing this as duplicate of #1640

**Closed as completed** 2020-05-20 18:45 UTC
