### ISSUE TITLE
Enhance User Guide to Detail Harvesting Setup

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4325] opened 2023-05-19 15:34 UTC
## User Story

In order to assist our agency partners, data.gov wants to enhance the user guide to include a segment on how to prepare an agency's data for harvesting and configure a harvest source.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN an agency would like to know how to publish data on data.gov
  THEN data.gov would like to provide a user guide written in plain language for how to do that.

## Background

Currently for those looking to publish data on data.gov, the only guide to harvesting config is this document: https://resources.data.gov/resources/data-gov-open-data-howto/

Data.gov would like to take the information in that post above, and update / revise it to make the process current and more transparent so that an agency can configure a harvest source with minimal help from data.gov admins.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

None 

## Sketch

- [ ] Edit this post here for any outdated info: https://resources.data.gov/resources/data-gov-open-data-howto/
- [ ] Create a section in new data.gov site for harvesting user guide. Append that to the current user guide or, minimally, provide a link at the top of the user guide to this new post
- [ ] Outline:
  - [ ] How to create a data.json file using the Inventory metadata form
  - [ ] How to configure and administer a harvest source
  - [ ] How to triage errors in the harvesting process

**Comment by hkdctol** [comment] 2023-10-20 20:36
Bringing in, taking into account the issue that came up the other day re CSW support

**Comment by hkdctol** [comment] 2023-12-21 16:09
Closing this as dupe of https://github.com/GSA/resources.data.gov/issues/651

**Closed as completed** 2023-12-28 23:19 UTC
