### ISSUE TITLE
catalog-harvester2d low disk space on root partition

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1687] opened 2020-05-20 15:47 UTC
%95 disk usage on /.

It is due to many xml files in `/tmp/s3sitemap` generated by cronjob `ckan-sitemap`. Some are 30 days old.

**Comment by mogul** [comment] 2020-05-28 20:46
We've got some time until this bugs us again after a manual clear; going to Icebox for now.

**Comment by adborden** [comment] 2020-06-04 23:52
I think this is a duplicate of https://github.com/GSA/datagov-deploy/issues/742. The root cause is that the s3sitemap job fails in staging and doesn't cleanup the generated files.

**Comment by pjsharpe07** [comment] 2020-06-15 21:50
Just ran into this issue again and did a manual cleanup of the `/tmp/s3sitemap` directory

**Comment by FuhuXia** [comment] 2020-08-14 15:45
Same issue today. Manually cleaned up `/tmp/s3sitemap`.

**Closed as completed** 2023-02-06 18:49 UTC
Labels: O&M

**Comment by nickumia-reisys** [comment] 2023-02-06 20:15
- https://github.com/GSA/data.gov/issues/3710
