### ISSUE TITLE
Fetch jobs running but not contributing to harvest process

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#2155] opened 2020-09-17 21:18 UTC
We have 6 `harvest-fetch` processes running simultaneously on production. When reviewing the supervisor status, they might all be `up` but are not contributing to any harvest fetch jobs.

## How to reproduce

1. Slightly difficult to reproduce. If a harvest job is in the `fetch` stage of harvesting and is running slowly, restarting all supervisor fetch processes significantly speeds up the harvest fetch stage.

Discovered during work on [a slow USGS harvest investigation issue](https://github.com/GSA/datagov-deploy/issues/1879).

## Expected behavior

Each harvest fetch process should be working on a job (if there are available jobs). If it isn't, supervisor should restart that harvest-fetch process.

## Actual behavior

When a harvest-fetch process is started, it may not pick up new harvest-fetch jobs.

**Comment by jbrown-xentity** [comment] 2021-03-02 18:20
Ran into this again today; created a new harvest source for DOI and still hadn't reported "started" after 12 hours.
Checked server logs, almost nothing in the fetch-consumer.log and gather-consumer.log. Restarted both processes (supervisor reported them being up for 2 days), and they immediately started logging doing work. Not sure why this occurred...

**Comment by FuhuXia** [comment] 2021-03-02 18:37
> Ran into this again today; created a new harvest source for DOI and still hadn't reported "started" after 12 hours.
> Checked server logs, almost nothing in the fetch-consumer.log and gather-consumer.log. Restarted both processes (supervisor reported them being up for 2 days), and they immediately started logging doing work. Not sure why this occurred...

related to https://github.com/GSA/datagov-deploy/issues/2862.
we have a 24-hour reset. wait for 24 hours and see whether something happens.

**Comment by jbrown-xentity** [comment] 2021-03-03 14:22
Ran into this again this morning. Logs show that nothing is happening for harvest gather or fetch since yesterday. Supervisor reports all processes as running. As soon as the gather process was restarted, jobs were picked up. I believe this is a bug, and will require manual intervention moving forward until resolved...

**Comment by adborden** [comment] 2021-03-03 16:43
Is this a duplicate of https://github.com/GSA/datagov-deploy/issues/796?

**Comment by jbrown-xentity** [comment] 2021-03-03 16:59
Closing as duplicate of #796.

**Closed as completed by jbrown-xentity** 2021-03-03 16:59 UTC
Labels: component/harvest, bug
