### ISSUE TITLE
Inventory-next dataset count is different from inventory

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2332] opened 2020-10-23 20:28 UTC
Inventory-next on migrated database shows inconsistent dataset count compared to original inventory.

## How to reproduce

Visit inventory and inventory-next site on staging as anonymous user and logged in user. Compare the count on datasets page.

## Expected behavior

Consistent count comparing inventory and inventory-next

## Actual behavior
dataset counts are inconsistent on datasets page:

inventory-next anonymous user: 300+
inventory-next logged in user: 10+K

inventory anonymous user: no access
inventory logged in user: 300+

**Comment by mogul** [comment] 2020-10-29 20:18
Let's first identify why the totals are different, then decide if one or the other is "correct".

**Comment by pjsharpe07** [comment] 2020-10-30 19:04
While working on #2362 we noticed that a logged in user with `editor` permissions only sees ~380 datasets on staging. It appears that only `sys-admin` users are seeing the 10+K numbers.

**Comment by jbrown-xentity** [comment] 2020-11-09 20:43
The datasets that are available to a logged in user on inventory-classic versus a generic user of inventory-next are almost identical, however there are 8 dataset differences. They are all some version of `test`, but see below for the complete list. Somehow the level of access is off by 1 for inventory-next, so where inventory-classic had no dataset access for an anonymous user, inventory-next anonymous user has access to the 300+ public datasets. And inventory-classic user has access to those 300, an inventory-next user has access to all datasets (13,685).

Dataset titles differences list (all items in inventory-next but missing from inventory-classic unless otherwise noted):
- datasettest12321
- dataset-test-datapusher
- dsfsdf
- my_dataset_name
- test100
- test222
- testdata20201021
- test-dataset-qa
- test-gsa-json (in inventory-classic but not next)

**Comment by FuhuXia** [comment] 2020-11-09 20:55
I am quite sure those listed dataset are manually created AFTER the migration, so they are supposed to be on one instance not the other.

**Comment by jbrown-xentity** [comment] 2020-11-09 21:53
The datasets are marked private at the CKAN level, which causes the different dataset access for each app. There are 384 active datasets marked with `private` being false in the DB, and 13301 datasets marked with `private` as true, which accounts exactly as our previous counts. You can verify by running the following query on the server:

```
SELECT
  COUNT(*),
  private
FROM package
WHERE state = 'active'
GROUP BY private;
```

**Comment by jbrown-xentity** [comment] 2020-11-09 22:03
The datasets that are currently public could easily be made private and locked down if necessary/desired. Still searching for the root cause as to why inventory-classic locks down datasets even at the sysadmin level...

**Comment by jbrown-xentity** [comment] 2020-11-09 22:24
In examining the api responses, I found that there is a new parameter in ckan2.8 api (compared to 2.5) for packages: [include_private](https://docs.ckan.org/en/2.8/api/index.html#ckan.logic.action.get.package_search). I believe some of the limitations for searching and querying were baked into CKAN2.5 to not be able to search private datasets even if you have access to them.
I believe this is simply formalizing the behavior that should have existed from the start, and inventory-next is the behavior I would expect. I propose to close this issue, but would love feedback on where/what to examine from here.

Curl commands:
```
curl -H "Authorization: my-personal-api-key" https://inventory-datagov.dev-ocsit.bsp.gsa.gov/api/3/action/package_search?rows=1
curl -H https://inventory-datagov.dev-ocsit.bsp.gsa.gov/api/3/action/package_search?rows=1
curl -H "Authorization: my-personal-api-key" https://inventory-next-datagov.dev-ocsit.bsp.gsa.gov/api/3/action/package_search?rows=1
curl https://inventory-next-datagov.dev-ocsit.bsp.gsa.gov/api/3/action/package_search?rows=1
```

**Comment by adborden** [comment] 2020-11-09 23:15
Okay, am I summarizing this issue correctly?

The difference in counts between inventory-next and inventory-classic is that in inventory-classic, sysadmins did not see private datasets in the count but in inventory-next, sysadmins see everything, including private datasets in the count.

If that's right, sounds like we're okay to close this.

**Comment by jbrown-xentity** [comment] 2020-11-10 14:33
That is the correct summary. Will move to done.

**Closed as completed** 2020-11-13 18:24 UTC
Labels: Inventory.data.gov
