### ISSUE TITLE
Inventory errors when download data.json file

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3365] opened 2021-08-02 13:19 UTC
Seeing errors when button "Unredacted Inventory" is clicked to download data.json file.
1. A zip file is generated but the file extension is `*.json`, therefore end user is not able to open the file.
2. Error message when downloading DOE data.json file
```
<type 'exceptions.AttributeError'> : blueprint.py : 145 : 'GroupExtra' object has no attribute 'split'
```
3. All datasets ends up in the errors.json when downloading GSA data.json file with same error message:
```
"errors": [["Invalid Required Field Value", ["The 'mediaType' field must be a string but it has a different datatype (<type 'str'>). (1 locations)"]], ["Missing Required Fields", ["The 'accessLevel' field is missing. (1 locations)", "The 'bureauCode' field is missing. (1 locations)", "The 'fn' field is missing. (1 locations)", "The 'hasEmail' field is missing. (1 locations)", "The 'identifier' field is missing. (1 locations)", "The 'modified' field is missing. (1 locations)", "The 'programCode' field is missing. (1 locations)"]]]
```
## How to reproduce

Download json file from DOE and GSA organization.

## Expected behavior

Successful zip file downloaded with data.json file in it.

## Actual behavior

Multiple errors as described.

## Sketch
- [x] Diagnose `blueprint.py` for error mentioned above.
- [x] Add test and code fix to ensure proper zip extension used in file name.
- [x] Add test and code fix for "Unredacted Inventory" data.json file download.
- [x] Add test and code fix for data.json file download when organization contains `sub-agencies` extra field.

**Comment by nickumia-reisys** [comment] 2021-08-02 13:35
Is this related to a recent py3 upgrade?  Was ckanext-datajson deployed to production?

These errors are probably related to the functionality added [here](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/blueprint.py#L233-L258).

**Comment by FuhuXia** [comment] 2021-08-02 13:44
> Is this related to a recent py3 upgrade? Was ckanext-datajson deployed to production?
> 
> These errors are probably related to the functionality added [here](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/blueprint.py#L233-L258).

Things were fine before the recent deployment to merge `feature/py3-py2-conditional`. So it should be related.

**Comment by nickumia-reisys** [comment] 2021-08-02 20:54
ckanext-usmetadata might have the same issue because it has the same [code block](https://github.com/GSA/ckanext-usmetadata/pull/53/commits/a835a2cdce9e68b17cf687a51c632f53ef7736aa) .... 😢

**Comment by FuhuXia** [comment] 2021-08-02 21:36
code rolled back on production. things are back to normal.

**Comment by FuhuXia** [comment] 2021-08-03 20:42
~~Will create a new issue to add tests and resolve for this scenario.~~
Added in the Sketch section.

**Comment by jbrown-xentity** [comment] 2021-09-14 14:12
This might be fixed in https://github.com/GSA/ckanext-datajson/pull/104/files. Tests have been built in cypress for CKAN2.9, should consider manually testing changes and/or utilizing cypress tests: https://github.com/GSA/inventory-app/pull/359/files#diff-ab4b110143d4b67e5a8a6f90bc6d4792448cb09ba8204dd74cc575feb365fec6R41-R53

**Comment by nickumia-reisys** [comment] 2021-09-14 14:36
1. The filename saving to `*.zip` is verified working based on James' last comment.  
2. Not sure, the extension would have to be retested.
3. Same as 2.

**Comment by jbrown-xentity** [comment] 2021-09-14 16:57
for 2, we would need to add multiple organizations. The top level org should have the following attributes:

- `"sub-agencies": "sub-agency1,sub-agency2"`

**Comment by mogul** [comment] 2021-09-16 21:02
We are having a hard time reproducing this without data in the database. We'll work on reproducing it with a dump from production.

**Comment by jbrown-xentity** [comment] 2021-09-20 17:22
Rollback is confirmed on production. Can download GSA data.json without issue, and can download DOE data.json without issue and it contains 400+ datasets (more than the DOE org itself, which is expected).

**Comment by jbrown-xentity** [comment] 2021-09-22 21:55
[This PR](https://github.com/GSA/inventory-app/pull/367) confirms Py3 is working as expected, and will be tested moving forward. Manually testing will be performed on a PR to validate CKAN2.8, pending...

**Comment by jbrown-xentity** [comment] 2021-09-22 22:09
Testing manually on sandbox, it looks like there are a lot of issues exporting fields to DCAT-US format. Will need to investigate further before ready for current production.

**Comment by jbrown-xentity** [comment] 2021-09-24 21:57
Documentation left for pinning datajson, ready for review.

**Closed as completed** 2021-09-30 19:54 UTC
Labels: bug
