### ISSUE TITLE
data.json harvester does not delete datasets that do not exist on the source

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4050] opened 2022-11-08 17:28 UTC
In harvest source https://catalog.data.gov/harvest/state-of-california, there are **500+** datasets do not exist on the source but failed to be deleted by harvesting jobs. For example, [this dataset](https://catalog.data.gov/dataset/annas-hummingbird-range-cwhr-b287-ds1535-4381d). 

The source data.json file https://data.ca.gov/data.json contains **2977** datasets,  but there are **3583** harvested. 

Looking at the gather log, when it checks existing dataset, it checks 2900+ records but ignore the 500+ ones including the sample one. It is not checked therefore it is not deleted.

A newly set up source in the Development space works fine.

**Comment by jbrown-xentity** [comment] 2022-12-08 21:29
Duplicate of #2989 , closing...

**Closed as completed by jbrown-xentity** 2022-12-08 21:29 UTC
Labels: bug
