### ISSUE TITLE
Catalog harvest page lost facet search items

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3928] opened 2022-08-17 20:10 UTC
Page https://catalog.data.gov/harvest used to have facet search items on the left column. They disappeared and are empty now.

## How to reproduce

https://catalog.data.gov/harvest

## Expected behavior

![image](https://user-images.githubusercontent.com/1392461/185233216-7c7d1b56-f2c7-494c-800a-f1ea3a0016e1.png)

## Actual behavior

![image](https://user-images.githubusercontent.com/1392461/185233250-6dd54f1a-d410-4d05-baff-285f1678cfbf.png)

## Sketch

- [ ] Look at recent changes, maybe with theme or geodatagov, or harvest extension

**Comment by nickumia-reisys** [comment] 2022-09-02 15:17
First pass at investigating issue:
- [ ] Checkout `catalog.data.gov@main` and see if the problem exists locally
- [ ] Checkout something around [August 15th](https://github.com/GSA/catalog.data.gov/commits/main) and see if the problem still exists
![image](https://user-images.githubusercontent.com/85196563/188180680-c6de918f-d038-4ff9-a17d-ed695f106ae7.png)
- [ ] If it doesn't, then check the PRs related to version updates for
  - [ ] ckanext-datgovtheme
  - [ ] ckanext-geodatagov
  - [ ] ckanext-harvest

**Comment by Jin-Sun-tts** [comment] 2022-09-08 21:18
Found the root cause of the issue, the fixes in the following PR cause the facet search item lost:

https://github.com/GSA/ckanext-datagovtheme/pull/123
related issue: https://github.com/gsa/data.gov/issues/3520

**Comment by Jin-Sun-tts** [comment] 2022-09-14 14:28
Fixed the issue with sync the facet_list.html file with the version in ckan2.9.5  
Pushed into PyPi with new version 0.1.7  
The catalog.data.gov requirement.txt file has the latest version with this fix now. 

This issue is fixed in production:
![Screen Shot 2022-09-14 at 10 23 07 AM](https://user-images.githubusercontent.com/104456257/190182262-3fb147b0-491a-4a94-b6fe-f9e466e629c9.png)

**Closed as completed** 2022-09-15 23:11 UTC
Labels: component/catalog, bug, UI/UX
