### ISSUE TITLE
omb_bureau_codes.csv needs to be migrated to resources.data.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1693] opened 2020-05-21 21:23 UTC
ckanext.geodatagov.bureau_csv.url=https://project-open-data.cio.gov/data/omb_bureau_codes.csv

## How to reproduce

1. Description of steps to reproduce the issue.

**Comment by mogul** [comment] 2020-05-28 20:51
We think this is done, just need to double-check before we close it.

**Comment by hkdctol** [comment] 2020-06-03 19:30
@pjsharpe07 I checked--we need to keep the pdf link and then delete the broken CSV link. once you do that this one can be considered closed

**Comment by hkdctol** [comment] 2020-06-03 19:33
@pjsharpe07 looks like the link below that--program code, has a broken link. will send you that CSV.

**Comment by pjsharpe07** [comment] 2020-06-04 15:27
Going to the [dcat section](https://resources.data.gov/schemas/dcat-us/v1.1/) or resources.data.gov, you can see the csv for bureauCodes removed and the programCode csv link has been fixed.

**Comment by adborden** [comment] 2020-06-04 22:37
@pjsharpe07 @hkdctol I think something got a little lost in translation here. catalog.data.gov needs the bureau codes CSV in order to generate this bureau filter on the search page. It's used by [ckanext-datagovtheme](https://github.com/GSA/ckanext-datagovtheme/search?q=bureau_csv&unscoped_q=bureau_csv). 

![Screenshot from 2020-06-04 15-32-04](https://user-images.githubusercontent.com/509703/83817066-b6b7b300-a678-11ea-92fe-b39c977dc526.png)

These filters link to URLs like https://catalog.data.gov/dataset?bureauCode=026%3A00

So the even if the bureau codes are obsolete, we need to do something to make sure they live somewhere other than project-open-data.cio.gov which is going away. Moving to resources.data.gov makes the most sense, unless we want to change the strategy altogether? We could drop the bureauCode filter or commit the CSV directly to ckanext-datagovtheme, we just need to write that story.

**Comment by hkdctol** [comment] 2020-06-04 22:43
OK. I missed that. I need to check something then, because the CSV I had, I'm not sure it is up to date. I may have to create one. I agree easiest thing would be to link to an accurate CSV from resources.data.gov.

**Comment by hkdctol** [comment] 2020-06-05 19:15
@pjsharpe07 will send you bureau code CSV, confirmed with OMB it's ok to use

**Comment by pjsharpe07** [comment] 2020-06-05 20:55
Once the PR above gets merged we can edit the ckanext-geodatagov repo and that will resolve this issue

**Comment by adborden** [comment] 2020-06-05 23:44
Once merged, you'll want to edit the production.ini templates in [datagov-deploy](https://github.com/GSA/datagov-deploy/search?q=filename%3Aproduction.ini.j2&unscoped_q=filename%3Aproduction.ini.j2).

**Comment by pjsharpe07** [comment] 2020-06-08 20:30
So, the [ckanext-geodatagov production.ini](https://github.com/GSA/ckanext-geodatagov/blob/d82eb45067f9b8335b6d767499f218431fb6c215/deployment/etc/ckan/production.ini#L106) doesn't need to be updated?

**Comment by adborden** [comment] 2020-06-09 23:56
It couldn't hurt, but honestly I don't think that file or the `deployment` directory is used for anything. The [README](https://github.com/GSA/ckanext-geodatagov/blob/d82eb45067f9b8335b6d767499f218431fb6c215/deployment/README) hasn't been updated since 2012 and refers to a process that definitely is not used today. All of our environments define the production.ini and ansible tasks in [datagov-deploy](http://github.com/GSA/datagov-deploy). Even the [extension tests](https://github.com/GSA/ckanext-geodatagov/blob/d82eb45067f9b8335b6d767499f218431fb6c215/.circleci/config.yml#L24) use a different config file ([docker_ckan.ini](https://github.com/GSA/ckanext-geodatagov/blob/d82eb45067f9b8335b6d767499f218431fb6c215/docker_test.ini)). Plus, the configuration item itself should probably be renamed to `ckanext.datagovtheme.bureau_csv` since it's not even ckantext-geodatagov that uses it, it's [ckanext-datagovtheme](https://github.com/GSA/ckanext-datagovtheme/blob/00ef64786cf5751eff18bbd468a913862698617c/ckanext/datagovtheme/helpers.py#L467).

Anyway, it's all very confusing. I would start with datagov-deploy and if the extension CI tests start failing later down the line, it will be more clear what other files need to be updated and how they should be cleaned up.

**Closed as completed** 2020-06-11 18:40 UTC
Labels: component/resources.data.gov, bug
