### ISSUE TITLE
Inventory fails to serve requests in sandbox: S3 not configured

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1061] opened 2019-10-22 22:46 UTC
S3 is not configured in sandbox environments, so requests fail to Inventory.

```
[Tue Oct 22 22:41:50.467031 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009] Traceback (most recent call last):
[Tue Oct 22 22:41:50.467046 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]   File "/etc/ckan/apache.wsgi", line 12, in <module>
[Tue Oct 22 22:41:50.467067 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]     _application = loadapp('config:%s' % config_filepath)
[Tue Oct 22 22:41:50.467075 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]   File "/usr/lib/ckan/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
[Tue Oct 22 22:41:50.467092 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]     return loadobj(APP, uri, name=name, **kw)
[Tue Oct 22 22:41:50.467098 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]   File "/usr/lib/ckan/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
[Tue Oct 22 22:41:50.467118 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]     return context.create()
[Tue Oct 22 22:41:50.467131 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]   File "/usr/lib/ckan/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
[Tue Oct 22 22:41:50.467143 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]     return self.object_type.invoke(self)
[Tue Oct 22 22:41:50.467149 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]   File "/usr/lib/ckan/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
[Tue Oct 22 22:41:50.467159 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]     return fix_call(context.object, context.global_conf, **context.local_conf)
[Tue Oct 22 22:41:50.467165 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]   File "/usr/lib/ckan/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
[Tue Oct 22 22:41:50.467175 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]     val = callable(*args, **kw)
[Tue Oct 22 22:41:50.467181 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]   File "/usr/lib/ckan-new/src/ckan/ckan/config/middleware.py", line 58, in make_app
[Tue Oct 22 22:41:50.467192 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]     load_environment(conf, app_conf)
[Tue Oct 22 22:41:50.467197 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]   File "/usr/lib/ckan-new/src/ckan/ckan/config/environment.py", line 232, in load_environment
[Tue Oct 22 22:41:50.467207 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]     p.load_all(config)
[Tue Oct 22 22:41:50.467212 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]   File "/usr/lib/ckan-new/src/ckan/ckan/plugins/core.py", line 134, in load_all
[Tue Oct 22 22:41:50.467221 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]     load(*plugins)
[Tue Oct 22 22:41:50.467227 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]   File "/usr/lib/ckan-new/src/ckan/ckan/plugins/core.py", line 166, in load
[Tue Oct 22 22:41:50.467235 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]     plugins_update()
[Tue Oct 22 22:41:50.467240 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]   File "/usr/lib/ckan-new/src/ckan/ckan/plugins/core.py", line 116, in plugins_update
[Tue Oct 22 22:41:50.467248 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]     environment.update_config()
[Tue Oct 22 22:41:50.467254 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]   File "/usr/lib/ckan-new/src/ckan/ckan/config/environment.py", line 403, in update_config
[Tue Oct 22 22:41:50.467262 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]     plugin.configure(config)
[Tue Oct 22 22:41:50.467267 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]   File "/usr/lib/ckan-new/src/ckanext-s3filestore/ckanext/s3filestore/plugin.py", line 38, in configure
[Tue Oct 22 22:41:50.467277 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]     ckanext.s3filestore.uploader.BaseS3Uploader().get_s3_bucket(
[Tue Oct 22 22:41:50.467283 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]   File "/usr/lib/ckan-new/src/ckanext-s3filestore/ckanext/s3filestore/uploader.py", line 29, in __init__
[Tue Oct 22 22:41:50.467292 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]     self.bucket = self.get_s3_bucket(self.bucket_name)
[Tue Oct 22 22:41:50.467298 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]   File "/usr/lib/ckan-new/src/ckanext-s3filestore/ckanext/s3filestore/uploader.py", line 44, in get_s3_bucket
[Tue Oct 22 22:41:50.467311 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]     S3_conn = boto.connect_s3(p_key, s_key)
[Tue Oct 22 22:41:50.467317 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]   File "/usr/lib/ckan/lib/python2.7/site-packages/boto/__init__.py", line 141, in connect_s3
[Tue Oct 22 22:41:50.467327 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]     return S3Connection(aws_access_key_id, aws_secret_access_key, **kwargs)
[Tue Oct 22 22:41:50.467333 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]   File "/usr/lib/ckan/lib/python2.7/site-packages/boto/s3/connection.py", line 190, in __init__
[Tue Oct 22 22:41:50.467343 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]     validate_certs=validate_certs, profile_name=profile_name)
[Tue Oct 22 22:41:50.467349 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]   File "/usr/lib/ckan/lib/python2.7/site-packages/boto/connection.py", line 569, in __init__
[Tue Oct 22 22:41:50.467359 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]     host, config, self.provider, self._required_auth_capability())
[Tue Oct 22 22:41:50.467364 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]   File "/usr/lib/ckan/lib/python2.7/site-packages/boto/auth.py", line 987, in get_auth_handler
[Tue Oct 22 22:41:50.467374 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009]     'Check your credentials' % (len(names), str(names)))
[Tue Oct 22 22:41:50.467392 2019] [:error] [pid 18246:tid 140377939097344] [remote 10.0.102.24:29009] NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials
```

## How to reproduce

1. https://inventory.ci.datagov.us/user/login

## Expected behavior

Login screen loads.

## Actual behavior

500 error, "NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. 
 ['HmacAuthV1Handler'] Check your credentials" error in /var/log/inventory/ckan.error.log

**Comment by adborden** [comment] 2019-12-05 02:13
As a work-around, you can disable the s3filestore extension.

**Comment by mogul** [comment] 2020-04-16 20:49
Closing as a dupe of #765.

**Comment by mogul** [comment] 2020-04-16 20:53
Reopening as this can be done on its own without worrying about the other apps.

**Comment by FuhuXia** [comment] 2020-05-13 19:06
These PRs get this issue resolved.  
https://github.com/GSA/datagov-infrastructure-live/pull/70
https://github.com/GSA/datagov-infrastructure-modules/pull/52
https://github.com/GSA/datagov-deploy/pull/1653

**Closed as completed** 2020-05-14 17:12 UTC
Labels: Inventory.data.gov, bug
