### ISSUE TITLE
Stuck harvest sources

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#953] opened 2019-09-13 16:16 UTC
There are a few harvest sources that repeatedly show up in our stuck harvest job report. Some investigation is needed on why these keep getting stuck.

- [SBA JSON](https://admin-catalog.data.gov/harvest/admin/sba-json)
- [USDA JSON](https://admin-catalog.data.gov/harvest/admin/usda-json)

## How to reproduce

1. Open the [harvest source](https://admin-catalog.data.gov/harvest/admin/sba-json) admin
1. Click Reharvest
1. Come back in 24 hours

## Expected behavior

Harvest job should complete in less than an hour.

## Actual behavior

Harvest job is still in the running state.

**Comment by FuhuXia** [comment] 2020-03-26 03:19
Found the reason for harvest job getting stuck. If the dataset contains certain string field that is too large to be indexed by Solr, it will generate an exception during fetch stage with error message: 
> bytes can be at most 32766 in length; got 309643. Perhaps the document has an indexed string field (solr.StrField) which is too large

on example of such field is `spatial`
![Screenshot 2020-03-25 23 02 48](https://user-images.githubusercontent.com/1392461/77606428-e1a1c000-6eed-11ea-9ce3-e1c9ffd5e885.png)

If the size of such string field can be evaluated during fetch stage, those datasets with string field larger than 32766 can be marked as ERROR state, so they won't stay at IMPORT state and get the whole harvest job stuck.

**Comment by FuhuXia** [comment] 2020-03-30 15:00
The cause for USDA harvest job getting stuck is explained above. For SBA's job, the cause is different. It is due to one dataset used the reserved word 'Search' as title. `['new', 'edit', 'search']` are reserved words and can't be used as title. ckanext-datajson has problem to deal with this exception. Will address these issues separately with two PRs.

**Comment by FuhuXia** [comment] 2020-03-30 17:02
PR for USDA fix https://github.com/GSA/ckanext-datajson/pull/58

**Comment by adborden** [comment] 2020-03-30 17:49
Can you see if the SBA issue has been raised upstream?
> It is due to one dataset used the reserved word 'Search' as title. ['new', 'edit', 'search'] are reserved words and can't be used as title

**Comment by FuhuXia** [comment] 2020-03-31 16:26
This SBA kind of error is well handled in other harvester. We only see it in `chanext-datajson` and we are the upstream (sort of). 
 
> Can you see if the SBA issue has been raised upstream?

**Comment by FuhuXia** [comment] 2020-04-01 16:40
PR for SBA fix https://github.com/GSA/ckanext-datajson/pull/60

**Closed as completed** 2020-05-14 16:53 UTC
Labels: component/catalog, bug
