### ISSUE TITLE
`catalog-fetch` cannot delete dataset?

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4419] opened 2023-08-07 14:51 UTC
## How to reproduce

1. Not sure...

Background:
- 8/4: Harvesting started
- 8/4-8/7: Stuck jobs occurred
- 8/7: Tried to investigate why there were 105 stuck jobs.. 
- 8/7: Re-ran `National Transportation Atlas Database (NTAD) Metadata` Harvest source
- 8/7: `ckan harvester run` worked fine in `catalog-admin`
- 8/7: `catalog-gather` processed the source fine (sent 100 datasets to `catalog-fetch`
- 8/7: `catalog-fetch` keeps getting the error in this ticket.
  - Note: These may be datasets from the "stuck" jobs... but I'm not sure how to valdiate that.

## Expected behavior

No error.

## Actual behavior

```
   2023-08-07T10:45:28.21-0400 [APP/PROC/WEB/2] OUT 2023-08-07 14:45:28,213 INFO  [ckanext.harvest.queue] Received harvest object id: 865fa754-5eb5-4d5d-a976-e591faec723e
   2023-08-07T10:45:28.25-0400 [APP/PROC/WEB/2] OUT 2023-08-07 14:45:28,253 DEBUG [ckanext.spatial.harvesters.base.import] Import stage for harvest object: 865fa754-5eb5-4d5d-a976-e591faec723e
   2023-08-07T10:45:28.25-0400 [APP/PROC/WEB/2] OUT 2023-08-07 14:45:28,253 DEBUG [ckanext.spatial.harvesters.base] Using config: {'validator_profiles': ['fgdc_minimal'], 'private_datasets': False}
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR Traceback (most recent call last):
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR File "/home/vcap/deps/1/bin/ckan", line 8, in <module>
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR sys.exit(ckan())
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR return self.main(*args, **kwargs)
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/click/core.py", line 1055, in main
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR rv = self.invoke(ctx)
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR return _process_result(sub_ctx.command.invoke(sub_ctx))
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR return _process_result(sub_ctx.command.invoke(sub_ctx))
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR return ctx.invoke(self.callback, **ctx.params)
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/click/core.py", line 760, in invoke
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR return __callback(*args, **kwargs)
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/cli.py", line 249, in fetch_consumer
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR utils.fetch_consumer()
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/utils.py", line 345, in fetch_consumer
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR fetch_callback(consumer, method, header, body)
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/queue.py", line 497, in fetch_callback
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR fetch_and_import_stages(harvester, obj)
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR File "/home/vcap/deps/1/src/ckanext-harvest/ckanext/harvest/queue.py", line 515, in fetch_and_import_stages
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR success_import = harvester.import_stage(obj)
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR File "/home/vcap/deps/1/src/ckanext-spatial/ckanext/spatial/harvesters/base.py", line 534, in import_stage
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR p.toolkit.get_action('package_delete')(context, {'id': harvest_object.package_id})
   2023-08-07T10:45:28.35-0400 [APP/PROC/WEB/2] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/logic/__init__.py", line 551, in wrapped
   2023-08-07T10:45:28.36-0400 [APP/PROC/WEB/2] ERR result = _action(context, data_dict, **kw)
   2023-08-07T10:45:28.36-0400 [APP/PROC/WEB/2] ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/logic/action/delete.py", line 90, in package_delete
   2023-08-07T10:45:28.36-0400 [APP/PROC/WEB/2] ERR raise NotFound
   2023-08-07T10:45:28.36-0400 [APP/PROC/WEB/2] ERR ckan.logic.NotFound
```

## Sketch

Need to ask @FuhuXia

**Comment by FuhuXia** [comment] 2023-08-18 15:28
Tested catalog-fetch works fine to delete datasets. Need to see it live to debug this issue. My guess is that the harvest_object `865fa754-5eb5-4d5d-a976-e591faec723e` has been deleted but when the job is stuck and forcefully finished, something did not sync correctly.

**Comment by btylerburton** [comment] 2023-08-31 18:19
Might be related to #4362

**Comment by FuhuXia** [comment] 2023-09-12 15:09
For the past 70+ days this happens in two time windows, cannot be easily be replicated. If we catch a new event, we can look in the context and try to figure out what triggers it, is it related to 
- a force-finished harvest job, 
- a manual run of dedupe
- a manaul run of harvest_object relink
- ...
Then we can go from there. For now, let us block this issue and check NewRelic log regularly for new event. 

![image](https://github.com/GSA/data.gov/assets/1392461/8a3f9745-9d66-47d0-b054-ddceb1d3003b)

**Comment by nickumia-reisys** [comment] 2023-10-09 14:10
@FuhuXia and I might have figured out why this happens during `waf` harvesting.  The issue is that it [looks up `url` to delete a package from the DB](https://github.com/ckan/ckanext-spatial/blob/master/ckanext/spatial/harvesters/waf.py#L79-L95).  During the gather stage, it creates a HO with the package to delete.  The HO gets sent to the fetch stage to delete it.  However, if the url was `null` from the DB lookup, then it fails to delete it.

P.S. I was actually able to have this discussion with @FuhuXia because of the experience documenting the pipeline 😄 
- https://github.com/GSA/data.gov/issues/4433

**Comment by FuhuXia** [comment] 2023-10-09 14:29
It happens when fetch is taking the harvest object ids and deleting packages... most deleting is fine but once in a while we see this error

```
OUT 2023-10-09 13:25:24,073 INFO  [ckanext.harvest.queue] Received harvest object id: 6841f47e-8f70-4e97-84d2-6619303db8dd
OUT 2023-10-09 13:25:24,109 DEBUG [ckanext.spatial.harvesters.base.import] Import stage for harvest object: 6841f47e-8f70-4e97-84d2-6619303db8dd
OUT 2023-10-09 13:25:24,109 DEBUG [ckanext.spatial.harvesters.base] Using config: {'private_datasets': False}
OUT 2023-10-09 13:25:26,549 INFO  [ckanext.spatial.harvesters.base.import] Deleted package f17b7086-a4e4-406e-9415-b7aa44bf4c3c with guid opendap.co-ops.nos.noaa.gov-urn_ioos_station_NOAA.NOS.CO-OPS_PWS0728
OUT 2023-10-09 13:25:26,569 INFO  [ckanext.harvest.queue] Received harvest object id: 199b8cf2-2b38-416f-9e48-ff28fd2d1135
OUT 2023-10-09 13:25:26,606 DEBUG [ckanext.spatial.harvesters.base.import] Import stage for harvest object: 199b8cf2-2b38-416f-9e48-ff28fd2d1135
OUT 2023-10-09 13:25:26,606 DEBUG [ckanext.spatial.harvesters.base] Using config: {'private_datasets': False}
OUT 2023-10-09 13:25:29,001 INFO  [ckanext.spatial.harvesters.base.import] Deleted package cf4557f9-3c9f-40b3-9e31-038bf40ceeed with guid wmo-42043
OUT 2023-10-09 13:25:29,016 INFO  [ckanext.harvest.queue] Received harvest object id: b1ea0d32-bacc-4161-b08a-d431d3f399ec
OUT 2023-10-09 13:25:29,049 DEBUG [ckanext.spatial.harvesters.base.import] Import stage for harvest object: b1ea0d32-bacc-4161-b08a-d431d3f399ec
OUT 2023-10-09 13:25:29,049 DEBUG [ckanext.spatial.harvesters.base] Using config: {'private_datasets': False}
OUT 2023-10-09 13:25:31,272 INFO  [ckanext.spatial.harvesters.base.import] Deleted package d41a82e1-0f51-4386-8aa3-7bfd1001df36 with guid NDFD_2016_Wind_Speed_Gust
OUT 2023-10-09 13:25:31,289 INFO  [ckanext.harvest.queue] Received harvest object id: a1958dfc-7b1c-448e-a5d2-249c1efa627f
OUT 2023-10-09 13:25:31,325 DEBUG [ckanext.spatial.harvesters.base.import] Import stage for harvest object: a1958dfc-7b1c-448e-a5d2-249c1efa627f
OUT 2023-10-09 13:25:31,325 DEBUG [ckanext.spatial.harvesters.base] Using config: {'private_datasets': False}
ERR Traceback (most recent call last):
...
ERR File "/home/vcap/deps/1/python/lib/python3.9/site-packages/ckan/logic/action/delete.py", line 90, in package_delete
OUT Exit status 1
```
By examming what package_id is in the DB, either a null or a real package, we will get close in knowing the impact of this error and how to resolve it.

**Comment by FuhuXia** [comment] 2023-10-10 13:47
DB inspected. The problemetic harvest object id contains a NULL package_id. So we need to figure out how a harvest object with NULL package_id is created, or ignore this kind of harvest object during fetch process, to avoid of this error.

**Comment by Jin-Sun-tts** [comment] 2023-10-25 21:36
![Screenshot 2023-10-25 at 5 36 43 PM](https://github.com/GSA/data.gov/assets/104456257/98133120-0a85-4092-b65c-419ee9a33486)


Found the code where to delete the package, will make sure the package_id is not null before doing the delete to avoid this error:

![Screenshot 2023-10-25 at 5 33 58 PM](https://github.com/GSA/data.gov/assets/104456257/567a8aca-21ac-4999-b47d-c276a51c532a)

will setup local harvest with WAF resource and test the fixes.

**Comment by Jin-Sun-tts** [comment] 2023-11-03 17:56
added a fix to avoid crash the harvester process, it is in branch v2-0-0-gsa in the fork GSA/ckanext-spatial/ (https://github.com/GSA/ckanext-spatial/pull/18)

will do more investigation to avoid harvest object with null package_id be added into the queue.

**Comment by Jin-Sun-tts** [comment] 2023-11-08 21:18
Upon checking in the production database, it was observed that there were 74,424 records with `NULL` `package_id` values while having `current` is `True` (which are incorrect/bad harvest objects). This situation caused the harvester process to crash due to the presence of NULL values in the `package_id` field.

Attempted to replicate this scenario on local environment in order to identify the underlying cause, but was unable to reproduce the situation for various test scenarios.

So decided to address the existing problematic harvest objects in the database for the time being and will closely monitor it to determine if the issue reoccurs.

First conducted a test on one of the harvest sources by resetting the `current` status to `False` when the `package_id` is `null`, and subsequently re-harvested it. This test yielded correct results, leading us to rectify all erroneous records in the database.

Closed this issue as the problematic data records have been rectified.

**Closed as completed by Jin-Sun-tts** 2023-11-08 21:18 UTC
Labels: bug
