### ISSUE TITLE
Catalog CKAN 2.8+ environment in sandbox

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#924] opened 2019-08-27 14:17 UTC
## User Story
As an operator, I want a basic CKAN 2.8 environment in sandbox running catalog (and harvesters) so that I can identify a clear upgrade path with working software.

## Details

In the past, we tried to start with a development environment running all of our custom extensions and work toward 2.8. Instead, we should start with vanilla 2.8 and begin adding essential Data.gov functionality.

## Acceptance Criteria
- [ ] Terraform templates for ckan environment

**Comment by adborden** [comment] 2020-03-21 00:24
Updated this issue to be about Catalog only, since Inventory has a new issue https://github.com/GSA/datagov-deploy/issues/1481

**Comment by kimwdavidson** [comment] 2020-04-13 15:30
Work for DevSecOps team

**Comment by mogul** [comment] 2020-04-30 20:31
Closing as a dupe of #1507

**Closed as completed by mogul** 2020-04-30 20:31 UTC
Labels: component/catalog
