### ISSUE TITLE
Run solr-sync job automatically on a schedule

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1595] opened 2020-04-23 20:36 UTC
[This issue is about running the solr-sync job regularly to take care of any problems that might result in CKAN and Solr being out of sync, eg what we see in #1542 .]

## User Story

As a [user description], I want [behavior description] so that [goal].

## Acceptance Criteria
- [ ]

**Comment by jbrown-xentity** [comment] 2020-10-01 22:19
Closing as duplicate of https://github.com/GSA/datagov-deploy/issues/2213

**Closed as completed by jbrown-xentity** 2020-10-01 22:19 UTC
Labels: O&M
