### ISSUE TITLE
datajson harvest shows Non-Federal Validation Schema on UI but harvested against Federal Validation

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3297] opened 2021-06-15 15:35 UTC
If you create a harvest source with datajson and non-federal validation, such as [the state of california](https://admin-catalog-next.data.gov/harvest/admin/state-of-california), the harvests all fail with federal validation.

## How to reproduce

1. Harvest non-federal datajson data

## Expected behavior

Appropriate validation is applied and expected errors are reported

## Actual behavior

Bureau Code and Program Code are required and fail, even though it shouldn't be.

## Sketch
Unknown. Need to try to reproduce locally with https://data.ca.gov/data.json, and try to discover why validation schema isn't being used appropriately.

**Comment by FuhuXia** [comment] 2021-06-29 17:00
The issue is due to this harvest source has no Validation Schema defined in the DB, so during harvesting it is validated against default federal validation. However, on the UI the default is non-federal validation. That is where the conflict comes from. We need to make UI and backend consistent.

**Comment by FuhuXia** [comment] 2021-06-29 22:01
Tested again. On UI the default selection is also federal validation. So no explanation why this harvest source was showing non-federal validation on UI even it was not. Probably some cache glitch that we will not see again. Close this until we see it again with another harvest source.

**Comment by sam-hayashi** [comment] 2021-06-30 19:03
Hi FuhuXia, I am the CA Open Data program lead and was wondering if this means your harvest of our portal should be working now? Please let us know if you need anything from our end. Thanks!

**Comment by FuhuXia** [comment] 2021-06-30 19:13
@sam-hayashi Yes, we don't see error message about `bureauCode` or `programCode` any more. However, there are other errors that need to be resolved on your end. You can capture the error by validating https://data.ca.gov/data.json against `non-federal-v1.1` at [Data.json validator tool](https://labs.data.gov/dashboard/validate). I can see mostly it is due to missing `mediaType` in the `distribution`.

**Comment by sam-hayashi** [comment] 2021-06-30 21:11
@FuhuXia - Thank you! We will work on getting that fixed as soon as possible. Do you happen to know the frequency of the harvests of our portal? Thanks!

**Comment by FuhuXia** [comment] 2021-06-30 21:17
@sam-hayashi The harvesting for https://data.ca.gov/data.json is set to run on weekly schedule. Last run was yesterday. So next run should be 7/6/2021.

**Comment by FuhuXia** [comment] 2021-07-23 14:47
Found another two harvest sources experiencing the same issue. Open the harvest source edit page, re-save it, re-harvest it, then everything is back to normal.
https://catalog.data.gov/harvest/md-json
https://catalog.data.gov/harvest/kingcounty-json

It turns out to be a wide spreaded issue affecting other 50 harvest sources. The UI is using the config value in table `package_extra`, while harvesting is using config value in table `harvest_source`. For the 50 harvest sources `"validator_schema": "non-federal"` is only in the UI.  

This query lists all the affected harvest sources.

```
SELECT h.id,  h.config, p.value
FROM harvest_source h
JOIN package_extra p
ON h.id = p.package_id
WHERE p.key = 'config'
AND h.config NOT LIKE '%non-federal%'
AND p.value LIKE '%non-federal%'
;
```

Since a simple re-saving on the UI will make two values same, the issue seems to have been fixed in the code. We will need to manually re-save it for 50 harvest sources, or run some DB query to update values in table `harvest_source` to be same as `package_extra` ,

**Comment by mogul** [comment] 2021-07-29 20:18
We'll generate a list of URLs from the DB, but then do the actual update by re-saving in the UI to ensure we won't circumvent any application logic or DB constraints for how updates should work.

**Comment by hkdctol** [comment] 2021-07-30 20:13
Yes, if it's a matter of manually re-saving through the UI, once there's a list that can be assigned to me or @crysacarter

**Comment by FuhuXia** [comment] 2021-07-30 20:35
Ok, there are 49 of them. 
Log in to catalog site, then access the following url and save.

1. https://admin-catalog-next.data.gov/harvest/edit/69491903-796a-4ce6-b376-da7b82772e7c
2. https://admin-catalog-next.data.gov/harvest/edit/8d269e22-ff3d-45d8-b878-47ef2aba7851
3. https://admin-catalog-next.data.gov/harvest/edit/b52daf01-e1d8-4b71-9c25-9750f1e425b8
4. https://admin-catalog-next.data.gov/harvest/edit/d747cd8f-d1d6-49a3-ab0b-ea17684f1121
5. https://admin-catalog-next.data.gov/harvest/edit/8046ced8-8d85-4a5f-9de9-c32b3e68eae7
6. https://admin-catalog-next.data.gov/harvest/edit/74e5aca6-5900-4fd4-9645-4c9648709c14
7. https://admin-catalog-next.data.gov/harvest/edit/d52781fd-51ef-4061-9cd2-535a0afb663b
8. https://admin-catalog-next.data.gov/harvest/edit/9036f762-5108-4f00-bdd5-523aa22fda7e
9. https://admin-catalog-next.data.gov/harvest/edit/7590e386-229e-453a-8e53-6f18e200e421
10. https://admin-catalog-next.data.gov/harvest/edit/1696593e-c691-4f61-a696-5dcb9e4c9b4c
11. https://admin-catalog-next.data.gov/harvest/edit/ba08fbb6-207c-4622-87d1-a82b7bd693ce
12. https://admin-catalog-next.data.gov/harvest/edit/3636b698-f3eb-4e93-a26e-b664cc785274
13. https://admin-catalog-next.data.gov/harvest/edit/a97b159c-d697-44bd-b7ba-3e777bd48a59
14. https://admin-catalog-next.data.gov/harvest/edit/f61de7a2-69cf-40a9-a1bc-dd9edb8f3fe5
15. https://admin-catalog-next.data.gov/harvest/edit/c5ee7104-80bc-4f22-8895-6c2c3755af40
16. https://admin-catalog-next.data.gov/harvest/edit/7154dab7-a9cc-48a0-9300-2d15e63fad34
17. https://admin-catalog-next.data.gov/harvest/edit/1c33d1cb-2f69-4f1b-835e-453790f38dc7
18. https://admin-catalog-next.data.gov/harvest/edit/4678ef15-545c-4c3b-be19-75d55f823605
19. https://admin-catalog-next.data.gov/harvest/edit/527363ff-de32-4b43-a73f-ed38fccdb66d
20. https://admin-catalog-next.data.gov/harvest/edit/8507fa43-f429-4095-b732-2177330ce485
21. https://admin-catalog-next.data.gov/harvest/edit/a49a5edc-d60e-48eb-a26f-3b29d5886786
22. https://admin-catalog-next.data.gov/harvest/edit/36c82f29-4f54-495e-a878-2c07320bf10c
23. https://admin-catalog-next.data.gov/harvest/edit/9cd19d43-dac0-4c36-a661-cee5dfcea6ab
24. https://admin-catalog-next.data.gov/harvest/edit/8ed9cb64-3f9c-4c51-a89f-7ec8140833a3
25. https://admin-catalog-next.data.gov/harvest/edit/2c4160c6-e27c-4df5-909e-f9c6c99a321d
26. https://admin-catalog-next.data.gov/harvest/edit/3b6df381-c8b4-40be-954e-84552dfba592
27. https://admin-catalog-next.data.gov/harvest/edit/c037b4d4-228d-4a00-b9dd-85d25e16fe12
28. https://admin-catalog-next.data.gov/harvest/edit/30d246cf-08ff-4754-a7b3-b2fbdb3011b5
29. https://admin-catalog-next.data.gov/harvest/edit/e2fea7c3-e835-4880-bb0b-ed41d5c6ac85
30. https://admin-catalog-next.data.gov/harvest/edit/47188674-2795-4157-8e65-22ba0509c622
31. https://admin-catalog-next.data.gov/harvest/edit/e89390e7-5e8a-4431-8a77-150118e1192b
32. https://admin-catalog-next.data.gov/harvest/edit/5e0e7936-9905-4d14-be00-72ea8f67d01f
33. https://admin-catalog-next.data.gov/harvest/edit/fb7d6b48-1744-461b-b995-a5a27afd2f4c
34. https://admin-catalog-next.data.gov/harvest/edit/fbb7bb4a-8e2a-46b6-8c02-efcd7c5297a7
35. https://admin-catalog-next.data.gov/harvest/edit/fe642abd-66eb-4c4f-af99-5858679fad30
36. https://admin-catalog-next.data.gov/harvest/edit/4719aee1-4278-47bc-9f5e-3752cb35586a
37. https://admin-catalog-next.data.gov/harvest/edit/d62c4cd7-f478-4110-ab03-adc778a15795
38. https://admin-catalog-next.data.gov/harvest/edit/7c55db6f-78c3-4120-a882-c4b8b0b43026
39. https://admin-catalog-next.data.gov/harvest/edit/ceea1675-8276-45f1-b45c-bb28dba71955
40. https://admin-catalog-next.data.gov/harvest/edit/bc39e510-cff7-4263-8d5b-7c800dd08cd6
41. https://admin-catalog-next.data.gov/harvest/edit/c85c8720-0b97-4586-ab30-f6be519b7ecb
42. https://admin-catalog-next.data.gov/harvest/edit/e2c1b013-5957-4c37-9452-7d0aafee3fcc
43. https://admin-catalog-next.data.gov/harvest/edit/9741faaf-ae6d-4b4a-9e05-0731e2e48f2f
44. https://admin-catalog-next.data.gov/harvest/edit/36f923f9-f915-42dc-a4de-1a5e3a17d284
45. https://admin-catalog-next.data.gov/harvest/edit/24b4ec67-cad4-4235-b8af-afaa3907ff2e
46. https://admin-catalog-next.data.gov/harvest/edit/49a7e9f8-1a28-41ce-9ea8-146d221bb34a
47. https://admin-catalog-next.data.gov/harvest/edit/df573dd9-dda2-439d-be4a-c5a3e9b0cc03
48. https://admin-catalog-next.data.gov/harvest/edit/87bb3350-882e-4976-978d-18d37298e268
49. https://admin-catalog-next.data.gov/harvest/edit/ded7e0b2-febc-49bb-af4c-ee572aa34770

**Comment by hkdctol** [comment] 2021-07-30 20:38
Great. @crysacarter let's go over this on Monday I think you'll be able to take care of this one.

**Comment by crysacarter** [comment] 2021-08-02 19:11
manually verifed as non-federal and saved 
exception https://admin-catalog-next.data.gov/harvest/edit/3636b698-f3eb-4e93-a26e-b664cc785274 - listed as WAF
and 
https://admin-catalog-next.data.gov/harvest/edit/c85c8720-0b97-4586-ab30-f6be519b7ecb -single spatial metadata document

Neither offered choice betweed federal and non-federal

**Comment by FuhuXia** [comment] 2021-08-02 19:29
@crysacarter I am still seeing about 40 of them not re-saved. Please make sure to hit the Save button regardless what is displayed on the UI. Let me know if you have any questions.

**Comment by crysacarter** [comment] 2021-08-02 20:04
@FuhuXia I've saved all links - please let me know if there are remaining issues

**Comment by FuhuXia** [comment] 2021-08-02 20:09
@crysacarter All looks good now. Thanks. This ticket can be closed.

**Closed as completed** 2021-08-02 20:34 UTC
Labels: component/catalog, component/harvest, bug, support
