### ISSUE TITLE
Py3 + CKAN 2.9 support for catalog.data.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3183] opened 2021-05-03 21:58 UTC
## User Story

In order to run on a supported version of Python and reduce the friction preventing us from staying up to date with new CKAN versions, the core catalog.data.gov application should be compatible with CKAN2.9 and Python 3.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background
[CKAN 2.9 migration notes](https://docs.ckan.org/en/2.9/changelog.html#v-2-9-0-2020-08-05)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
- [ ] `ckan db upgrade`
- [ ] [Upgrade Solr schema to CKAN 2.9](https://docs.ckan.org/en/2.9/changelog.html#migration-notes)
- [ ] Update who.ini
- [ ] Open additional issues for non-essential [migration tasks](https://docs.ckan.org/en/2.9/changelog.html#migration-notes)
- [ ] Create another issue for the inventory app based on this one.

**Comment by mogul** [comment] 2021-08-30 18:41
Dupe of #3401

**Closed as completed by mogul** 2021-08-30 18:41 UTC
