### ISSUE TITLE
Use upstream datapusher

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1184] opened 2019-12-05 00:42 UTC
## User Story

As a Data.gov developer, I want to use the upstream Datapusher so that I don't have to maintain [code](https://github.com/GSA/datapusher) with unnecessary hacks.

## Details
https://github.com/ckan/datapusher/compare/master...GSA:master contains bumps to dependencies, some http/https hacks which are wrong, and the [Content-Type hack](https://github.com/GSA/datagov-deploy/issues/1177). These should not be necessary.

## Acceptance Criteria
- [ ] Ansible playbooks are updated to include simple install of upstream Datapusher.
- [ ] Any required fixes are pushed upstream.

**Comment by mogul** [comment] 2020-03-19 20:40
Closing as duplicate of #1422

**Closed as completed by mogul** 2020-03-19 20:40 UTC
Labels: Inventory.data.gov
