### ISSUE TITLE
BUG: ⇝ HelperError: Helper 'archiver_is_resource_broken_line' has not been defined.

### ISSUE THREAD

**Issue by starsinmypockets** [GSA/data.gov#1690] opened 2020-05-21 01:07 UTC
## Steps to reproduce:

View dataset resource

## Error

```
URL: http://ckan:5000/dataset/the-panel-study-of-income-dynamics-psid/resource/ad5b0e83-e617-41fa-b260-9f0bef7541b4
File '/usr/lib/python2.7/site-packages/weberror/evalexception.py', line 429 in respond
  app_iter = self.application(environ, detect_start_response)
File '/usr/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/lib/python2.7/site-packages/fanstatic/publisher.py', line 234 in __call__
  return request.get_response(self.app)
File '/usr/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/usr/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
  response = request.get_response(self.app)
File '/usr/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/srv/app/src/ckan/ckan/config/middleware/pylons_app.py', line 262 in inner
  result = application(environ, start_response)
File '/usr/lib/python2.7/site-packages/beaker/middleware.py', line 73 in __call__
  return self.app(environ, start_response)
File '/usr/lib/python2.7/site-packages/beaker/middleware.py', line 156 in __call__
  return self.wrap_app(environ, session_start_response)
File '/usr/lib/python2.7/site-packages/routes/middleware.py', line 131 in __call__
  response = self.app(environ, start_response)
File '/srv/app/src/ckan/ckan/config/middleware/common_middleware.py', line 30 in __call__
  return self.app(environ, start_response)
File '/srv/app/src/ckan/ckan/config/middleware/common_middleware.py', line 56 in __call__
  return self.app(environ, start_response)
File '/usr/lib/python2.7/site-packages/pylons/wsgiapp.py', line 125 in __call__
  response = self.dispatch(controller, environ, start_response)
File '/usr/lib/python2.7/site-packages/pylons/wsgiapp.py', line 324 in dispatch
  return controller(environ, start_response)
File '/srv/app/src/ckan/ckan/lib/base.py', line 240 in __call__
  res = WSGIController.__call__(self, environ, start_response)
File '/usr/lib/python2.7/site-packages/pylons/controllers/core.py', line 221 in __call__
  response = self._dispatch_call()
File '/usr/lib/python2.7/site-packages/pylons/controllers/core.py', line 172 in _dispatch_call
  response = self._inspect_call(func)
File '/usr/lib/python2.7/site-packages/pylons/controllers/core.py', line 107 in _inspect_call
  result = self._perform_call(func, args)
File '/usr/lib/python2.7/site-packages/pylons/controllers/core.py', line 60 in _perform_call
  return func(**args)
File '/srv/app/src/ckan/ckan/controllers/package.py', line 1147 in resource_read
  return render(template, extra_vars=vars)
File '/srv/app/src/ckan/ckan/lib/base.py', line 125 in render
  return cached_template(template_name, renderer)
File '/usr/lib/python2.7/site-packages/pylons/templating.py', line 249 in cached_template
  return render_func()
File '/srv/app/src/ckan/ckan/lib/base.py', line 162 in render_template
  return render_jinja2(template_name, globs)
File '/srv/app/src/ckan/ckan/lib/base.py', line 94 in render_jinja2
  return template.render(**extra_vars)
File '/usr/lib/python2.7/site-packages/jinja2/environment.py', line 989 in render
  return self.environment.handle_exception(exc_info, True)
File '/usr/lib/python2.7/site-packages/jinja2/environment.py', line 754 in handle_exception
  reraise(exc_type, exc_value, tb)
File '/srv/app/src/ckan/ckanext/datastore/templates/package/resource_read.html', line 1 in top-level template code
  {% ckan_extends %}
File '/srv/app/src/ckanext-datagovtheme/ckanext/datagovtheme/templates/package/resource_read.html', line 46 in top-level template code
  {% set pkg = c.pkg_dict %}
File '/srv/app/src/ckan/ckan/templates/package/resource_read.html', line 3 in top-level template code
  {% set res = c.resource %}
File '/srv/app/src/ckanext-datagovtheme/ckanext/datagovtheme/templates/package/base.html', line 3 in top-level template code
  {% set pkg = c.pkg_dict %}
File '/srv/app/src/ckanext-datagovtheme/ckanext/datagovtheme/templates/page.html', line 1 in top-level template code
  {% ckan_extends %}
File '/srv/app/src/ckan/ckan/templates/page.html', line 1 in top-level template code
  {% extends "base.html" %}
File '/srv/app/src/ckanext-harvest/ckanext/harvest/plugin/../templates/base.html', line 1 in top-level template code
  {% ckan_extends %}
File '/srv/app/src/ckanext-datagovtheme/ckanext/datagovtheme/templates/base.html', line 1 in top-level template code
  {% ckan_extends %}
File '/srv/app/src/ckan/ckan/templates/base.html', line 101 in top-level template code
  {%- block page %}{% endblock -%}
File '/srv/app/src/ckan/ckan/templates/page.html', line 19 in block "page"
  {%- block content %}
File '/srv/app/src/ckan/ckan/templates/page.html', line 22 in block "content"
  {% block main_content %}
File '/srv/app/src/ckan/ckan/templates/page.html', line 53 in block "main_content"
  {% block pre_primary %}
File '/srv/app/src/ckan/ckan/templates/package/resource_read.html', line 22 in block "pre_primary"
  {% block resource %}
File '/srv/app/src/ckan/ckan/templates/package/resource_read.html', line 24 in block "resource"
  {% block resource_inner %}
File '/srv/app/src/ckan/ckan/templates/package/resource_read.html', line 27 in block "resource_inner"
  {% block resource_actions %}
File '/srv/app/src/ckan/ckan/templates/package/resource_read.html', line 29 in block "resource_actions"
  {% block resource_actions_inner %}
File '/srv/app/src/ckan/ckanext/datastore/templates/package/resource_read.html', line 4 in block "resource_actions_inner"
  {{ super() }}
File '/srv/app/src/ckanext-datagovtheme/ckanext/datagovtheme/templates/package/resource_read.html', line 25 in block "resource_actions_inner"
  {{ h.archiver_is_resource_broken_line(c.resource) }}
File '/usr/lib/python2.7/site-packages/jinja2/environment.py', line 412 in getattr
  return obj[attribute]
File '/srv/app/src/ckan/ckan/lib/helpers.py', line 87 in __getitem__
  key=key
HelperError: Helper 'archiver_is_resource_broken_line' has not been defined.
```

**Comment by starsinmypockets** [comment] 2020-05-29 15:40
Related to https://github.com/GSA/datagov-deploy/issues/1426

**Comment by starsinmypockets** [comment] 2020-05-29 15:41
The helper is provided by the GSA fork of the archiver. We can remove this line to eliminate this error but should determine how the archiver is being used and whether it should be included in the MVP.

**Comment by starsinmypockets** [comment] 2020-05-29 15:43
https://github.com/GSA/ckanext-datagovtheme/blob/bc16aedab2096217e01003d1ac2122009c46b225/ckanext/datagovtheme/templates/package/resource_read.html#L25

**Comment by estebanruseler** [comment] 2020-06-04 16:19
Moved to done as this issue is a duplicate of #46 and #46 is done

**Comment by adborden** [comment] 2020-06-04 23:16
@starsinmypockets @estebanruseler are we really done here? My understanding is that https://github.com/GSA/catalog.data.gov/issues/46 is only a work-around in that it disables the feature. But what @starsinmypockets describes here is that we still want to understand if that disabled behavior is still needed or not. Are we tracking that somewhere else?

**Comment by avdata99** [comment] 2020-06-05 13:30
> Are we tracking that somewhere else?

@adborden, we are tracking this (and the `ckanext-qa` function hidden) at [#50](https://github.com/GSA/catalog.data.gov/issues/50).

**Closed as completed** 2020-06-12 17:16 UTC
Labels: bug
