### ISSUE TITLE
Add login.gov saml2auth for catalog in cloud.gov

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2809] opened 2021-02-12 20:07 UTC
## User Story

As a catalog admin, I want login to be secured by a compliant service (like cloud.gov) so that we are in compliance.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN catalog is deployed in the cloud.gov prod space \
  WHEN I click the Login button happens \
  THEN I am redirected to Login.gov \
  AND user is created on successful return to the application

## Background
[Catalog should be deployed ](https://github.com/GSA/datagov-deploy/issues/2604)
[without saml2auth](https://github.com/GSA/catalog.data.gov/pull/240/files#diff-c1a3353682e43a2c8ffdd28ee390bd42a55f97db6f3456233bd4529239473239L125). See sketch.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
Needed for compliance, but no special security concerns in the development work.

## Sketch
Need to
- [ ] Create [login.gov application for catalog dev](https://dashboard.int.identitysandbox.gov/)
- [ ] [Create the cert and key](https://github.com/GSA/datagov-deploy/issues/2220#issuecomment-730502211)
- [ ] [Read into/out of secrets user-provided-service](https://github.com/GSA/datagov-deploy/wiki/Cloud.gov-Cheat-Sheet#secrets-management)
- [ ] Configure other necessary files, deployment of inventory via ansible is [here](https://github.com/GSA/datagov-deploy/pull/2648)

**Comment by adborden** [comment] 2021-02-20 00:28
Closing as a duplicate of https://github.com/GSA/datagov-deploy/issues/2777

**Closed as completed by adborden** 2021-02-20 00:28 UTC
