### ISSUE TITLE
Catalog-web2d fails on common playbook

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#1911] opened 2020-07-22 22:26 UTC
## How to reproduce

1. If you run the common/site playbook on catalog-web2d, you will see the playbook fail [during these commands](https://github.com/GSA/ansible-os-ubuntu-14/blob/master/tasks/section3.yml#L127-L152)

## Expected behavior

Common/site playbooks run without error and the host functions correctly.

## Actual behavior

Playbook fails and host does not function correctly.

## Current workaround

You can run `pipenv run ansible-playbook site.yml --limit catalog-web2d* --skip-tags "id_3.3.1,id_3.3.2`

**Comment by mogul** [comment] 2020-07-24 18:37
This will be hit every release until it's been resolved.

**Comment by mogul** [comment] 2020-07-24 18:39
@FuhuXia suggests that this might be best resolved by just reprovisioning this EC2 instance rather than working around it in code.

**Comment by FuhuXia** [comment] 2020-08-03 18:54
Re-launched the EC2 instance and ran the ansible playbooks. The issue is resolved.

**Closed as completed** 2020-08-06 18:32 UTC
Labels: component/common, bug
