### ISSUE TITLE
Inventory-next datapusher not working

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2186] opened 2020-09-24 21:36 UTC
Inventory-next datapusher is misconfigured. The app reports as running, but cycles/crashes every 30 seconds, and never responds to any requests.

```
[2020-09-24 21:02:35 +0000] [27741] [INFO] Worker exiting (pid: 27741)
[2020-09-24 21:02:35 +0000] [27810] [INFO] Booting worker with pid: 27810
/usr/lib/datapusher/lib/python2.7/site-packages/gevent/builtins.py:96: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  result = _import(*args, **kwargs)
 * Serving Flask app "ckanserviceprovider.web" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[2020-09-24 21:03:05 +0000] [26892] [CRITICAL] WORKER TIMEOUT (pid:27810)
```

Currently blocking sandbox jenkins deployment (#2180)
## How to reproduce

1. Attempt to upload any csv data to https://inventory-next.sandbox.datagov.us/dataset

## Expected behavior

Service is running and responds to requests

## Actual behavior

No response.

## Sketch/Mitigations
Have found that the system [does attempt to use the database](https://github.com/GSA/datagov-deploy/blob/develop/ansible/roles/software/ckan/inventory/templates/etc/ckan/datapusher_settings.py#L16-L20). Created necessary users and database, did not help. Next steps are to triage inventory-classic for database details.

**Comment by jbrown-xentity** [comment] 2020-09-24 21:41
Current datapusher DB info (inventory-classic):
```
datapusher=> \d
                    List of relations
 Schema |          Name           |   Type   |   Owner    
--------+-------------------------+----------+------------
 public | apscheduler_jobs        | table    | datapusher
 public | apscheduler_jobs_id_seq | sequence | datapusher
 public | jobs                    | table    | datapusher
 public | logs                    | table    | datapusher
 public | metadata                | table    | datapusher
```
Not sure if this is created automatically or built manually.

**Comment by jbrown-xentity** [comment] 2020-09-24 22:32
Calling it for today, [branch changes](https://github.com/GSA/datagov-deploy/pull/2183) were overwritten by release process. Still not sure why service is failing, but probably has something to do with `ckanservice` module and the database configuration...

**Comment by jbrown-xentity** [comment] 2020-09-25 15:23
Something is going wrong with the ckanservice module and gunicorn. Gunicorn just kills the process after 30 seconds, something to do with no change (with no information on what went wrong, it just kills the process). We are way deep in the weeds on this, and I don't see us making any upstream requests to either of those repositories at this point. 

Am going to roll back to WSGI deployment... While [the docs](https://docs.ckan.org/projects/datapusher/en/latest/deployment.html) say you can use either gunicorn or wsgi, the console gives a warning message: 
```
WARNING: This is a development server. Do not use it in a production deployment.`
Use a production WSGI server instead.
```

**Comment by jbrown-xentity** [comment] 2020-09-25 17:45
[Latest deploy works](https://inventory-next.sandbox.datagov.us/dataset/next-dataset/resource/3635ff0f-a6db-435e-9697-260cd3c393d0) :tada: 
Will merge to develop and verify all systems still working before marking as ready for deploy.

**Comment by jbrown-xentity** [comment] 2020-09-28 17:42
All necessary PR's are merged, final cleanup is pending #2208 . Ready for deployment...

**Comment by chris-macdermaid** [comment] 2020-10-16 18:08
Datapusher fails when uploading a file with the new template. Datapusher uploads the file correctly with the old template.
Opened an issue for the new template error. https://github.com/GSA/datagov-ckan-multi/issues/488

**Comment by chris-macdermaid** [comment] 2020-10-21 18:30
The reason this is failing is because of a CKAN bug with extensions that have a public/static directory . This was caught by the multi team.

https://github.com/GSA/datagov-ckan-multi/issues/390

**Comment by pjsharpe07** [comment] 2020-10-30 18:12
While working on #2362, we confirmed this on staging. New form fails datapusher upload, however following these steps will successfully create a resource with datapusher.

Assuming you have permissions to add datasets (ie org editor)
- Navigate to dataset landing page: ie https://inventory-next-datagov.dev-ocsit.bsp.gsa.gov/dataset/<your-dataset-name>
- Select `manage` --> `resources` --> `Add new resource`
- Select `Upload a file` and complete remaining form


fwiw, this workflow does not use the new metadata form

**Comment by adborden** [comment] 2020-10-31 00:56
I think we can close this issue since datapusher is working. The bug @pjsharpe07 is referring to is with the resource_create API call (and we think ckanext-s3filestore being at the root of it) and the issue is captured in https://github.com/GSA/datagov-ckan-multi/issues/488.

**Closed as completed** 2020-11-13 18:24 UTC
Labels: Inventory.data.gov, bug
